### ISSUE TITLE
Move selection up/down

### ISSUE THREAD

**Issue by User4martin** [Alexey-T/ATSynEdit#1]
Select some text in the last line. Then move sel up, down, down
Alt up, alt down, alt down

This inserts a new empty line. It can be repeated to add many new lines

**Comment by Alexey-T** [comment]
Tks for report. I ll see it

**Comment by Alexey-T** [comment]
i have fake line: empty Item with end=cEndNone; added after last ln, if last ln has end<>cEndNone. Moving up makes fake ln.  I know: i won't move down into fake ln, so this fixes

**Comment by Alexey-T** [comment]
done
