### ISSUE TITLE
Inserting a column mode selection at end of file creates extra empty line

### ISSUE THREAD

**Issue by User4martin** [Alexey-T/ATSynEdit#11]
Start with this text in the editor

1: Aa < eol>
2: Ba < eol>
3: Ca < eol>
4:

column mode select
A
B
C

place caret on line 4 (the last empty line with no EOL
paste
1: Aa < eol>
2: Ba < eol>
3: Ca < eol>
4: A < eol>
5: B < eol>
6: C < eol>
7: < eol>
8:

Line 7 should not be there.

**Comment by Alexey-T** [comment]
Confirm..

**Comment by Alexey-T** [comment]
Btw feel-free to open issue if closed/unfixed

**Comment by Alexey-T** [comment]
done
