### ISSUE TITLE
SynFacilSyn for ATSynEdit

### ISSUE THREAD

**Issue by t-edson** [Alexey-T/ATSynEdit#111]
Hi Alex.

In order to get familiarized with ATSynEdit, and for test his functionality first, I would like to make a version of my highlighter SynFacilSyn for ATSynEdit. Do you think is it possible?.

**Comment by Alexey-T** [comment]
Hi again.Yes possible.Of corse... see http://wiki.freepascal.org/ATSynEdit about "adapters" (part of page). It ok?

**Comment by Alexey-T** [comment]
(also `demo_editor` has simple OnCalcHilite)

**Comment by Alexey-T** [comment]
What you think?
