### ISSUE TITLE
auto-complete

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATSynEdit#112]
@BBasile - do u think autocomplete APi needed for ctrl+Space? IDE must have it. I want to add it.What other api must be for IDE? CoEdit?

**Comment by BBasile** [comment]
Yes of course needed for
- completion menu
- substitution macro (in coedit for example type `$i` then `import` is inserted)

I also use keystrokes macro recording and syncro editing.

BTW i tested the D Lexer and it's clearly outdated (some keywords miss, the first script line is not handled, a lot of literal are not recognized. Performance are acceptable. I also follow the TSynFacil guy to see if he'll manage to make an adapter.  (#111)

**Comment by Alexey-T** [comment]
Tks. I want to fix D. Can u make new topic? list in it a) b) .... 
With short test strings in D (few lines, each item)

**Comment by Alexey-T** [comment]
I make it--
 
![acp](https://cloud.githubusercontent.com/assets/4154978/9561610/ef913632-4e54-11e5-8f33-45d43e18c44d.png)

**Comment by Alexey-T** [comment]
@BBasile  @t-edson
http://wiki.freepascal.org/ATSynEdit#How_to_show_auto-complete_lists.3F

**Comment by t-edson** [comment]
Good functionality. But I prefer the way SynFacikSyn do completion. The list of words is defined in the same XML syntax file. So it uses the same lexer of the highlighter, to capture the tokens, and can access to the block information, so it can be a context-sensitive completion.

**Comment by Alexey-T** [comment]
U don't understand. see wiki about autocomplete--u CAN do complete like SynFacil !

**Comment by Alexey-T** [comment]
It's engine of listbox. Can do list like SynFacil
