### ISSUE TITLE
the D lexer for eControl is incomplete

### ISSUE THREAD

**Issue by BBasile** [Alexey-T/ATSynEdit#113]
- several keywords miss.

- string litteral post fixes (c\w\d) should be colorized as with the string:
`auto str = "char postfix"d `

- a bar can be used in each number form to improve readability
`auto num = 0xFF_FF_FF_FF`;

- int literal postfixes:
`auto a0 = 1U; auto a1 = 1u ;auto a2 = UL`

- the first script line is not handled. This should be processed as a comment (but only if line index is 1 (1-based).
`#!if the line number is 1 then this is ignored` 

Read more on each specific point [here](http://dlang.org/lex.html).
I'll add more later.

**Comment by Alexey-T** [comment]
I want to fix.When i do: pls call Synwrite AddonManager, reinstall D lexer. It updates then
1) What keywords to add.

**Comment by Alexey-T** [comment]
Is it ok?
http://uvviewsoft.com/bb/lexer.D.zip
(no AddonManager update)

**Comment by BBasile** [comment]
float literal starting with a period and ending with the **f** or **F** postfixes are not well handled:

```D
auto f = .123f;
auto f = .123F
```

These keywords are not covered:

```D
    bool byte

    cdouble cent cfloat creal

    dchar double
   
    false float

    idouble int ifloat ireal

    null
    
    real

    short
    true

    ubyte ucent  uint   ulong ushort
    
    void
    
    wchar

    // library types that could be HL has KW
    string
    wstring
    dstring
    size_t
    ptrdiff_t

```

**Comment by BBasile** [comment]
hex strings are not well handled. The **x** suffix should be colorized with the string litteral:

```D
auto a = x"46 48 49";
```

well neither GH HL does...but the x should be the same color as the remaining part of the litteral.

**Comment by Alexey-T** [comment]
>>    wstring dstring size_t
Hilite Ok already. no? I see purple color. special kind for "types": not black bold
I have 3 lists of KWs. KWs + "types" purple + "__FILE__" light-blue

**Comment by Alexey-T** [comment]
update. /bb/ folder. x-strings HL ok.

**Comment by BBasile** [comment]
I think i've reach a bug in CUDA, HL is not working anymore on a small file i use to test the HL.

![nomorehl](https://cloud.githubusercontent.com/assets/7805501/9561223/c9ceaf50-4e3c-11e5-80e6-cf83766890b1.png)

**Comment by Alexey-T** [comment]
statusbar: Lexer name "d" is here? or "-" here? D must be active in status

**Comment by BBasile** [comment]
oh...I see, that's embarassing. But for some reason it's not set automatically.

So
* x strings are ok now
* among the keywords from my previous list, not all of them are KW for a type: **null** **true** **false** **void** are not types.

That said, as a user i prefer to have types colorized as normal keywords. I can do that by hand in a customized HL.

Othherwise it's ok, unless i missed another detail.

**Comment by Alexey-T** [comment]
* null true false void: fix, update in 5min.

**Comment by Alexey-T** [comment]
>i prefer to have types colorized as normal keywords

Cudatext can do it. LexProp dialog. style-tab..

**Comment by BBasile** [comment]
Ok. Everything is fine now. Maybe i'll reopen if i've forgot something.

**Comment by Alexey-T** [comment]
Ok good
