### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATSynEdit#12]
... at end, better now. 20 carets now fast -1M file, at end. Slower editing if newlines added; no newlines--fast. @User4martin

**Comment by User4martin** [comment]
Nice but leaks (in wrap code)

Call trace for block $1B5A8D48 size 24
  $0043D5FE line 957 of ../../atsynedit/atsynedit.pas
  $0043D267 line 891 of ../../atsynedit/atsynedit.pas
  $00446C3D line 64 of ../../atsynedit/atsynedit_cmd_handler.inc
  $004476C1 line 234 of ../../atsynedit/atsynedit_cmd_handler.inc
  $00446AC3 line 24 of ../../atsynedit/atsynedit_cmd_handler.inc
  $005504CB line 5908 of include/wincontrol.inc
  $0054DE1D line 4955 of include/wincontrol.inc
  $00518BEF line 1095 of win32/win32callback.inc
Call trace for block $1B5A7A88 size 24
  $0043D5FE line 957 of ../../atsynedit/atsynedit.pas
  $0043D267 line 891 of ../../atsynedit/atsynedit.pas
  $00446C3D line 64 of ../../atsynedit/atsynedit_cmd_handler.inc
  $004476C1 line 234 of ../../atsynedit/atsynedit_cmd_handler.inc
  $00446AC3 line 24 of ../../atsynedit/atsynedit_cmd_handler.inc
  $005504CB line 5908 of include/wincontrol.inc
  $0054DE1D line 4955 of include/wincontrol.inc
  $00518BEF line 1095 of win32/win32callback.inc
Call trace for block $1B5A8CE8 size 24
  $0043D5FE line 957 of ../../atsynedit/atsynedit.pas
  $0043D267 line 891 of ../../atsynedit/atsynedit.pas
  $00446C3D line 64 of ../../atsynedit/atsynedit_cmd_handler.inc
  $004476C1 line 234 of ../../atsynedit/atsynedit_cmd_handler.inc
  $00446AC3 line 24 of ../../atsynedit/atsynedit_cmd_handler.inc
  $005504CB line 5908 of include/wincontrol.inc
  $0054DE1D line 4955 of include/wincontrol.inc
  $00518BEF line 1095 of win32/win32callback.inc
Call trace for block $1B5A8C28 size 24
  $0043D5FE line 957 of ../../atsynedit/atsynedit.pas
  $0043D267 line 891 of ../../atsynedit/atsynedit.pas
  $00446C3D line 64 of ../../atsynedit/atsynedit_cmd_handler.inc
  $004476C1 line 234 of ../../atsynedit/atsynedit_cmd_handler.inc
  $00446AC3 line 24 of ../../atsynedit/atsynedit_cmd_handler.inc
  $005504CB line 5908 of include/wincontrol.inc
  $0054DE1D line 4955 of include/wincontrol.inc
  $00518BEF line 1095 of win32/win32callback.inc

**Comment by Alexey-T** [comment]
leak fixd.
