### ISSUE TITLE
Python: collapsed "if/else/...." shows empty fold-mark

### ISSUE THREAD

**Issue by CudaText-addons** [Alexey-T/ATSynEdit#128]
collapsed "class/def" Ok.
others - not ok.
empty fold-mark.
![py](https://cloud.githubusercontent.com/assets/17549064/15564374/9421798a-2322-11e6-934a-fac02272eaef.png)

**Comment by Alexey-T** [comment]
reason: collapsed-mark format "%sz0". but "%s0 %s-1" works. why "%sz0" dont?
