### ISSUE TITLE
column mode selection in wrapped line (with wrap-indent) shows ghost selection

### ISSUE THREAD

**Issue by User4martin** [Alexey-T/ATSynEdit#13]
start a column mode selection on the first part (first wrap part, before any wrap) of a wrapped line.

There will be a 2nd visible selection marker in the indent area on the next line of the wrapped text.

**Comment by Alexey-T** [comment]
idea===make selection always from x1/y1 to x2/y2, raw columns, no tab counted, no wrap counted. This means this issue- it not issue.  make wrap OFF - u see correct selection? yes. i know it weird for WrapOn

**Comment by Alexey-T** [comment]
idea means- u make sel rect from x1 of "first part" to x2 of "wrap part" so it gives weird look.

**Comment by User4martin** [comment]
I still see an issue.
The visible markup is different from what will be copied.

If  I create a column mode selection over several wrapped lines, then on each wrapped line their is a selection shown (ghost).

But if I copy and then paste, nothing gets copied for the ghost. That is wrong.

![2015-04-21 03_27_58-demo - fn txt](https://cloud.githubusercontent.com/assets/7429624/7244642/80987428-e7d6-11e4-98de-b4a451eb4732.png)

See the image, text wraps at 20, tab size = 8
It will copy the following in the clipboard:
bc
23
oo

But the visible (blue) mark show many rows with empty content. Where are they?

Solution 1: They get copied (e.g. with spaces)
Solution 2: They are not highlighted

**Comment by Alexey-T** [comment]
Must not hilite, i should fix -tks

**Comment by Alexey-T** [comment]
Worked.Ghost right-side still here, ghost on indent gone

**Comment by Alexey-T** [comment]
Fixed for ghost on indent prt
