### ISSUE TITLE
page-dn jump

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATSynEdit#14]
Как настроить, чтобы
- каретка оставалась на том же месте экрана,
- последняя видимая строка файла стала первой видимой

Попробовал ставить и size и size-1 -- каретка прыгает из первой строки экрана в нижнюю. @kvichans

**Comment by Alexey-T** [comment]
Fix/введена опция "page-dn keep relative pos"/проверьте мейл

**Comment by kvichans** [comment]
Получил
А почему уже второй раз у архива расширение ZIPP ?
АК

=============

**Comment by Alexey-T** [comment]
А гугол отшивает zip, если у вас он, или у кого

**Comment by kvichans** [comment]
Проверил. Стало хорошо
