### ISSUE TITLE
DoCommand_TextInsertEOL logic

### ISSUE THREAD

**Issue by EganSolo** [Alexey-T/ATSynEdit#150]
Alex,
In the TATSynEdit.DoCommand_TextInsertEOL, there's this bit of code:

  for i:= FCarets.Count-1 downto 0 do
  begin
    Caret:= FCarets[i];
    Str:= GetAutoIndentString(Caret.PosX, Caret.PosY);
    Strings.TextInsertEol(Caret.PosX, Caret.PosY, AKeepCaret, Str, Shift, PosAfter);
    DoCaretsShift(Caret.PosX, Caret.PosY, Shift.X, Shift.Y, PosAfter);
    Caret.PosX:= PosAfter.X;
    Caret.PosY:= PosAfter.Y;
  end;

Here's the concern: If someone selects a block of lines and hits return, then Strings.TextInsertEOL will insert a line after the first line which will mess-up this block carets. I'd suggest you disable this function in case a block is selected because it actually does not make sense to select a block and hit the return key.

**Comment by Alexey-T** [comment]
hi;
pls use markdown, for code.
EOL: pls install Cudatext. do you see its Return key, woks bad? i select bnlock, press enter. and block deleted, new eol made.

**Comment by EganSolo** [comment]
Sorry, my bad. Did not see the downto... make sense. I will test more thoroughly next time. Thanks for suggestion :)
