### ISSUE TITLE
Extensibility suggestion: Quick and easy to implement with very little impact.

### ISSUE THREAD

**Issue by EganSolo** [Alexey-T/ATSynEdit#151]
[atstrings.zip](https://github.com/Alexey-T/ATSynEdit/files/736748/atstrings.zip)

Alexey, 

As I write my own highlighter with my own parser for TATSynedit, it occurred to me that a quick change in the **TATStrings** code would go a long way. Perhaps I've misread this and if so, you might suggest a better way.

Consider the method 
```pascal
procedure TATStrings.LineInsertRaw(N: integer; const AString: atString; AEnd: TATLineEnds);
var
  Item: TATStringItem;
begin
  if FReadOnly then Exit;
  if DoCheckFilled then Exit;

  DoAddUndo(cEditActionInsert, N, '', cEndNone);
  DoEventLog(N, Length(AString));
  DoEventChange(N, cLineChangeAdded);

  Item:= TATStringItem.Create_Uni(AString, AEnd); // <== This line.
  FList.Insert(N, Item);
end;
```
Would it be possible to replace 
```pascal
 Item:= TATStringItem.Create_Uni(AString, AEnd);
``` 
with 
```pascal
 Item:= NewUNIStringItem(AString,AEnd);
```
Where NewUNIStringItem is a protected virtual method that in TATSynEdit is implemented as
```pascal 
Function TATStrings.NewUNIStringItem(const aString: atString; aEnd: TATLineEnds): TATStringItem;
begin
   Result := TATStringItem.Create_Uni(AString,AEnd);
end;
```
The similar statement in TATStrings.LineAddRaw would be replaced in the same way.

Likewise, the statement
```pascal
FList[N+i] := TATStringItem.Create_UTF8(TaTStringItem(AList.Flist[i].ItemString,Endings)
```
would be replaced by
```pascal
FList[N+i] := NewUTF8StringItem(AList.Flist[i].ItemString,Endings);
```

The methods TATStrings.LineAddRaw, 
If this were possible, I could then extend TATStringItem and add properties I require to speed the highlight and the fold. 

What do you think?

Naturally, there should be a way to expose those line items from within the TATStrings object. For this, I've added a protected property called StringItem which is readonly to provide that access.

For your convenience, I've gone ahead and made those changes which you'll find in the zipped file. Search on the conditional define EganSoloModified and you'll find all the spots where I made that change.

**Comment by Alexey-T** [comment]
I will do it;change like in your file, better names.

**Comment by Alexey-T** [comment]
see the last diff.

**Comment by EganSolo** [comment]
Thanks Alexey! Great. I will.
