### ISSUE TITLE
Can the highlighter and parser work with ansi string?

### ISSUE THREAD

**Issue by EganSolo** [Alexey-T/ATSynEdit#152]
Alexey,

When handling OnEditorCalcHilite, I use ALineIndex to access the string currently changing like so:
```pascal
var Editor : TATSynEdit;
      S : String; //ansi string
begin
  Editor := TATSynEdit(Sender);
  S := Editor.Strings.Lines[ALineIndex];
```
When I do that, I get a warning from the compiler: 
Warning: Implicit string type conversion with potential data loss from "UnicodeString" to "AnsiString"

Does this mean that the only way to write a highlighter for TATSynEdit is to work with Unicode strings? If so, this would mean that the parser must also work with unicode strings as well.

I wouldn't mind this but I'm having some issues with SysUtils routines such as PosEx, LowerCase, Trim etc when I use switchmode UnicodeStrings.

Do you have any suggestions?

**Comment by Alexey-T** [comment]
> the only way to write a highlighter for TATSynEdit is to work with Unicode strings? If so

yes: in event you get UnicodeString. But other code may use ansistring, and convert  it  to Unicodestring. by Utf8Encode/Utf8Decode..

**Comment by Alexey-T** [comment]
You need PosEx, e.g., for Unicodestring. Else u cannot find russia "Б" in string

**Comment by Alexey-T** [comment]
So no issue here...
