### ISSUE TITLE
fExternal

### ISSUE THREAD

**Issue by EganSolo** [Alexey-T/ATSynEdit#153]
Alexey,

I noticed that the destructor of TATSynEdit does not free FStringsExternal. Is this the intended design?
Would it make sense to add a property to TATSynEdit that would specify whether the editor owns fStringsExternal so that it can free them in its destructor?

**Comment by Alexey-T** [comment]
IMO this is intended design, StringsExternal is freed by code of program, when you close program,
only StringInt is auto-freed, ie, StringExternal set from program code, freed

**Comment by Alexey-T** [comment]
sorry, maybe you can show code of program, which sets StringsExternal.

**Comment by EganSolo** [comment]
Well, the idea is that I need to extend the Strings class to include more attributes for purposes of highlighting. The only way to do so is to assign my derived class to StringsExternal. The thing though is that these StringsExternal could be shared by more than one Editor so therefore they must be reference counted so that as the editors are freed the StringsExternal are not destroyed until all editors have been removed.

So, yes, I can see why StringsExternal could be owned by the programmer who would be responsible to deallocate them when it make sense. Alternatively, they could be owned by the editors and reference counted. I can go either way.

**Comment by Alexey-T** [comment]
Now StringsExternal are removed by app,not by component, reference count is not needed here (eg, Ed1.Strings:= Ed2.Strings, StringsExternal is deleted when you delete Ed2)
