### ISSUE TITLE
Change TATRange.Add or TATRange.Insert into functions?

### ISSUE THREAD

**Issue by EganSolo** [Alexey-T/ATSynEdit#154]
Alexey,
Both TATRange.Add rely on fList.Add to add the new range. Now fList returns the index of that range. Why not pass it back? In other words, you could change TATRange.Add  into functions that return the index.

Does this make sense?

**Comment by Alexey-T** [comment]
Sorry, i cannot find TATRange.add in atsynedit_ranges.pas;
Maybe it's ok...

**Comment by EganSolo** [comment]
Sorry, it's TATRanges.Add, not TARange.add

**Comment by Alexey-T** [comment]
> Now fList returns the index of that range. Why not pass it back?

I thinked, we have Ranges.Count-1 which is index of last item. it is same as result of FList.Add
