### ISSUE TITLE
Why can't we expand a fold?

### ISSUE THREAD

**Issue by EganSolo** [Alexey-T/ATSynEdit#155]
Alexey,
Why are the coordinates of a fold TATSynRange read-only? Why can't we change them? 
Consider a use case where the user wrote a block comment ( (* ... *) in pascal). and suppose the user adds a line in the middle of this comment. Why can't we simply increment the Y2 value of that fold? As it is, it seems that we have to (a) delete the fold and (b) insert a new one. 

Just curious.

**Comment by Alexey-T** [comment]
coordinates of ATSynRAnge not read-only,
```
  TATSynRange = class
  private
    FX, //start column
    FY, //start line
    FY2: integer; //end line which is fully folded (can't partially fold)
    FFolded: boolean;
    FStaple: boolean;
    FHint: string;
  public
    property X: integer read FX;
    property Y: integer read FY;
    property Y2: integer read FY2;
```

**Comment by EganSolo** [comment]
I got that. I'm asking why are they read-only? Why not read-write?

**Comment by Alexey-T** [comment]
> got that. I'm asking why are they read-only? Why not read-write? 
Sorry, now i got it: i made x/y/y2 read-writeble

**Comment by Alexey-T** [comment]
>there does not seem to be any necessity in deleting a range instead of updating its boundaries.

You suggest to update range's coords. ok. maybe you can make a patch, which does it. I see it later
