### ISSUE TITLE
Need change position for TAB-arrow

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/ATSynEdit#16]
Хорошо, что длина TAB-стрелки стала настраиваться. Но сейчас короткая стрелка выровнена по центру своего отрезка. Это не позволяет понять в какой колонке вставлен символ TAB 
![tab-arrow](https://cloud.githubusercontent.com/assets/7419630/7089857/7c993042-dfa7-11e4-9c2f-38f05bcb004c.JPG)
Нужно выравнивать "влево", чтобы явно обозначать колонку

**Comment by Alexey-T** [comment]
Окей,хорошо
