### ISSUE TITLE
Wrong scrolling by DoGotoPos

### ISSUE THREAD

**Issue by martok** [Alexey-T/ATSynEdit#163]
When I try to scroll to the last line after adding text by code, the position scrolled to is 2 lines off.
```
  ATSynEdit1.Strings.LineAdd('Some Text');
  ATSynEdit1.DoCaretSingle(1, ATSynEdit1.Strings.Count-2, true); // why -2? -1 does not work.
  ATSynEdit1.DoGotoPos(ATSynEdit1.Carets.CaretAtEdge(cEdgeBottom), cScrollIndentCaretHorz, cScrollIndentCaretVert);
```
Scrolling by moving the cursor with the keyboard works fine.

If there are any Gaps in view, the position scrolled to is additionally wrong by the height of these gaps.

**Comment by Alexey-T** [comment]
It is ok. coz you didnt call ed.Update(true) after adding a line via Strings obj. Try with ed.Update

**Comment by Alexey-T** [comment]
Gaps - is another issue? It still here after ed.Update(true)?

**Comment by martok** [comment]
Update(true) does not change the behaviour at all. I actually have it in my code, removed it here for the minimal test case because there is absolutely no change whether I call Update before or after scrolling.

My test case is simply an ATSynEdit and a Button on a form, all settings left as defaults, then add lines until scrolling is required:
```
procedure TForm1.Button1Click(Sender: TObject);
var
  idx: Integer;
begin
  idx:= ATSynEdit1.Strings.Count - 1;  // Must use -1 because there is one more line reported than present
  ATSynEdit1.Strings.LineAdd('New Line '+IntToStr(idx));
  if idx mod 5 = 0 then                           // test: add gap every 5 lines
    ATSynEdit1.Gaps.Add(idx, 8, nil, 0);
  ATSynEdit1.Update(true);
  ATSynEdit1.DoGotoPos(Point(0, idx), 5, 5);
end;
```
The first issue appears to depend on some relation between display height, and line height, the scrolled position looks different ie. with ruler enabled or not.

The gap issue is 100% reproducible.

**Comment by Alexey-T** [comment]
offtop: " Must use -1 because there is one more line reported than present   "- ATSynEdit has "fake line" to show somthing on empty text, see `Strings.**Fake**`

**Comment by Alexey-T** [comment]
Can you confirm this code is ok?
```
procedure TForm1.Button1Click(Sender: TObject);
var
  idx: Integer;
begin
  idx:= ed.Strings.Count-1;
  ed.Strings.LineAdd('New Line '+IntToStr(idx));
  if idx mod 5 = 0 then                           // test: add gap every 5 lines
    ed.Gaps.Add(idx, 8, nil, 0);
  ed.Update(true);
  Application.ProcessMessages;
  ed.DoGotoPos_AndUnfold(Point(0, ed.Strings.Count-1), Point(-1, -1), 5, 5);
end;
```

**Comment by martok** [comment]
This code with DoGotoPos_AndUnfold works okay (but only with the ProcessMessages), using DoGotoPos with otherwise the same code misses half a line.

**Comment by Alexey-T** [comment]
Seems i forgot to place DoCaretSingle inside DoGotoPos

**Comment by Alexey-T** [comment]
See commit, i improved DoGotoPos (not fixed yet bug with Gaps)

**Comment by Alexey-T** [comment]
found the reason--- code must use OptLastLineOnTop=true. if you use Gaps.
else scrollbar dont allow correct scroll at file END [it middle- ok].
In demo its ok now with gaps:
```
procedure TForm1.Button1Click(Sender: TObject);
var
  idx: Integer;
begin
  idx:= ed.Strings.Count-1;
  ed.Strings.LineAdd('Line '+IntToStr(idx+1));

  if idx mod 5 = 0 then // test: add gap every 5 lines
    ed.Gaps.Add(idx, 20, nil, 0);

  ed.Update(true);
  Application.ProcessMessages;

  ed.DoGotoPos(
    Point(0, ed.Strings.Count-1), Point(-1, -1), 5, 5, true, true);
end;
```
