### ISSUE TITLE
Todo for fold-ranges

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATSynEdit#165]
Fold-ranges

-add "tag" to ranges
-if tag>0, don't remove this range before lexer parsing
-if tag>0, adapt range's y/y2 to added/deleted lines
(range must move down on insert lines above range)

Test with lexer, w/o lexer.

**Comment by EganSolo** [comment]
Alexy, could you also consider changing the two procedures TATSynRanges.Add and TATSynRanges.Insert into functions that return the newly added Range? I've done the change (it's pretty straightforward) and I've attached the ATSynEdit_Ranges unit below with that change in place.

[atsynedit_ranges.zip](https://github.com/Alexey-T/ATSynEdit/files/1189018/atsynedit_ranges.zip)

```pascal
{$IfDef EganSoloDef}
function TATSynRanges.Add(AX, AY, AY2: integer; AWithStaple: boolean; const AHint: string): TATSynRange;
begin
  Result := TATSynRange(FList.Add(TATSynRange.Create(AX, AY, AY2, AWithStaple, AHint)));
end;

function TATSynRanges.Insert(Index: integer; AX, AY, AY2: integer; AWithStaple: boolean;
                             const AHint: string) : TATSynRange;
begin
  FList.Insert(Index, TATSynRange.Create(AX, AY, AY2, AWithStaple, AHint));
  Result := Items[Index];
end;
{$Else}
```

**Comment by EganSolo** [comment]
Also, just wondering whether replacing the TList by a TSortedList would speed up the lookup required for these ranges?

**Comment by Alexey-T** [comment]
I think SortedList won't help. ranges not easy to sort.
I made change of result type: pls see.

**Comment by EganSolo** [comment]
Thanks Alexey. Will download and test.

**Comment by Alexey-T** [comment]
Tag:int64 is added to ranges. others: later.
