### ISSUE TITLE
OnChangeBlock event patch

### ISSUE THREAD

**Issue by EganSolo** [Alexey-T/ATSynEdit#167]
Hi Alexey,

I've been hard at work on my end to prep my code to fit into ATSynEdit. I'm almost there. Today, I pulled the latest code and I introduced a few modifications which I would like to propose:

I've enclosed all the changes within 
``` pascal
{$IfDef NMChanges} {$EndIf}
```
The affected files are:
1. ATStrings
2. AtStrings_Editing.inc
3. ATSynEdit_Gaps

The changes I'm proposing are non-destructive. They introduce one event to signal when a block is changing as follows:
``` pascal
//In the file ATSynEdit_Gaps beginning from line 22:
{$IfDef NMChanges}
  TATBlockChangeKind = (
    cBlockDeleteLines,
    cBlockInsertLines,
    cBlockDeleteColumnBlock,
    cBlockInsertColumnBlock
  );
{$EndIF}
```
This enumeration indicates the kind of block activities about to be performed. That's the only change in ATSynEdit_Gaps.

Next, in ATStrings beginning with line 90:
``` pascal
  {$IfDef NMChanges}
  TATBlocksChangeEvent = procedure (Sender    : TObject;
                                    aStartPos , anEndPos: TPoint;
                                    AChange   : TATBlockChangeKind;
                                    Block     : TStrings = Nil) of object;
  {$Endif}
```
This even type would be used to hook into the strings object and handle events that act on blocks.

Then, on line  132, within the TATStrings class:
``` pascal
    {$IfDef NMChanges}
    FBlockModeActive : Boolean;
    FOnBlockChange   : TATBlocksChangeEvent;
    {$EndIf}
```
The FOnBlockChange is the event handler. The FBlockModeActive is used to signal that any lines being deleted or added occur inside a block activity. This will allow the highlighter to focus only on syntax coloring and avoid any structural updates to its internal data structures such as updating line numbers.

On line 284
``` pascal
    {$IfDef NMChanges}
    property OnBlockChange: TATBlocksChangeEvent read FOnBlockChange write FOnBlockChange;
    {$EndIf}
```
This is the declaration for the event.

Line 625, inside TATStrings.Create
``` pascal
  {$IfDef NMChanges}
  FBlockModeActive := False;
  {$EndIf}
```
The fBlockModeActive is set to false when the TATStrings object is created.

This completes the list of changes in the file ATStrings. Last, here is the list of changes in atstrings_edit.inc. As you shall see, they are straightforward and do not modify existing logic.

First, from line 43: 
``` pascal
function TATStrings.TextReplaceLines_UTF8(ALineFrom, ALineTo: integer;
  ANewLines: TStringList): boolean;
var
  i: integer;
  {$IfDef NMChanges}
   aStartPos, anEndPos : TPoint;
  {$EndIf}
begin
  Result:= false;
  if not IsIndexValid(ALineFrom) then exit;
  Result:= true;

  BeginUndoGroup;
  try
    {$ifDef NMChanges}
      If assigned(FOnBlockChange)
      then begin
        FBlockModeActive := True;
        aStartPos.X := 1;
        aStartPos.Y := aLineFrom;
        anEndPos.X  := 0;
        anEndPos.Y  := Min(aLineTo,Count-1);
        fOnBlockChange(Sender,aStartPos,anEndPos,cBlockDeleteLines);
      end;
    {$EndIf}
    for i:= Min(ALineTo, Count-1) downto ALineFrom do
      LineDelete(i);

   {$ifDef NMChanges}
     If assigned(FOnBlockChange)
     then begin
       aStartPos.X := 0;
       aStartPos.Y := aLineFrom;
       anEndPos.X  := 0;
       anEndPos.Y  := 0;
       fOnBlockChange(Sender,aStartPos,anEndPos,cBlockInsertLines,aNewLines);
     end;
   {$EndIf}
    for i:= ANewLines.Count-1 downto 0 do
      LineInsert(ALineFrom, UTF8Decode(ANewLines[i]));
  finally
    {$IfDef NMChanges}
     FBlockModeActive := False;
    {$EndIf}
    EndUndoGroup;
  end;
end;
```
As you can see, the changes send a signal before the lines are deleted and before the lines are added. This then allows the syntax highlighter to traverse its data structure once and update the start and end of every block of code once only.

You will find the same logic applied in
1. TATStrings.TextInsert
2. TATStrings.TextDeleteRange
3. TATStrings.TextInsertColumnBlock

To better understand the use case of these changes, a bit of explanation on the way I handle changes would be helpful.

For every file of code, I maintain a separate data structure consisting primarily of an interval tree. Each interval is a block of code such as a procedure, a function, a class declaration,  etc. These intervals are non-intersecting and include other intervals.

Whenever the user inserts a new line, I look for that line in the tree and add 1 to the line of every block starting and/or ending position that are after the line that has been inserted. When one line is inserted, I traverse the tree once. But when a block is inserted, if I don't have the block events listed above, I must rely on the cLinesXXX events. 

Suppose I have a unit I am editing with say 2,000 lines of codes, 
[atsynedit_changedfiles.zip](https://github.com/Alexey-T/ATSynEdit/files/1120663/atsynedit_changedfiles.zip)

which translate into 200 intervals in my tree.
Suppose the user decides to insert at line 1 code the user copied from another file. Let's say this block contains 200 lines of codes.

Without the cBlocksXXX events, I will have to handle the InsertLine event 200 times. Each time, For each line insertion, I am updating the start and end position of all 200 intervals (recall we're inserting the block at the start of the file) 200 times. Since the interval tree contains 200 blocks, that 200 * 200 * 2 (begin and end positions updates which equal 80,000 updates.

With the cBlock events. I will know that I am inserting a block of size 200. I can then traverse the tree once and update the start/end position once and update each start/end position by 200, which equal 200 updates.

Would love to hear what you think,

Thanks,

Egan

**Comment by Alexey-T** [comment]
quick notes:

- OnChangeBlock name is better (sorted nice in ide)
- why to use _gaps file? [_gaps file is about gaps only]. why not to put types to ATStrings file?
- did you consider mul-carets? e.g. if 3 carets: empty, small block, big block.

**Comment by Alexey-T** [comment]
>FBlockModeActive is used to signal that any lines being deleted or added occur inside a block activity. 

If you dont use BlockModeActive, patch is not ok? why this var needed?

**Comment by Alexey-T** [comment]
[Del question about BlockModeActive, ok]

**Comment by Alexey-T** [comment]
Patch added; tks
Pls review [I changed it hard] and test -I didnt test.
i changed AFromPos.X from 1 to 0, we have offsets from 0.

**Comment by EganSolo** [comment]
Thanks Alexey
I will test! 
Please note that the only reason I used _gaps file is that it seems that ATStrings references that file for the definition of the  TATLineChangeKind = (
    cLineChangeEdited,
    cLineChangeAdded,
    cLineChangeDeleted,
    cLineChangeDeletedAll
    );                     

I thought it would make sense to drop the TATBlockChangeKind there. If that's not the right placement, I'm sure you'd have moved it.
Agreed OnChangeBlock is better.
Did not consider multi-carets. I wanted to see if we could get the block bit going first. I'll need to better understand the behavior of multi-carets first before I can figure out how to send events.

**Comment by Alexey-T** [comment]
Ok, waiting for your testing of patch in real life.

**Comment by vhanla** [comment]
Couldn't compile on Windows. 
Tested on Lazarus 1.8.0RC2 (FPC 3.0.2) and 1.9.0 (FPC 3.0.0). 

Error message: 
`atstrings_editing.inc(58,16) Fatal: Syntax error, ")" expected but "," found` 
On `Point` call which prioritizes `fpcsrc\rtl\win\wininc\struct.inc` instead of `fpsrc\rtl\objpas\classes\classesh.inc` so `Point` is NOT a function but a structure (record  `POINT = record   x : LONG;    y : LONG;      end; `).
```pascal
if Assigned(FOnChangeBlock) then
      FOnChangeBlock(Self,
        Point(0, ALineFrom), { <— error here }
        Point(0, Min(ALineTo, Count-1)), { <— error here and similar Point calls as function}
        cBlockDeleteLines,
        nil);
```
It is due to including `{$ifdef windows} Windows {$endif}` on ATString.pas file in Uses section, but it is just a matter of prepending `Classes.` before calling `Point` function.
e.g.
```pascal
 if Assigned(FOnChangeBlock) then
      FOnChangeBlock(Self,
        Classes.Point(0, ALineFrom), { <— Classes. }
        Classes.Point(0, Min(ALineTo, Count-1)),
        cBlockDeleteLines,
        nil);
```
Naturally, on Linux is OK (Lazarus 1.8.0RC2 and FPC 3.0.3).

**Comment by Alexey-T** [comment]
Ok, I got idea. made fix to uses-sections, pls try again.
