### ISSUE TITLE
How to set Label for issue?

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/ATSynEdit#17]
Не могу сообразить,  как назначить Label на пост
- Создаю новый
- Ввожу заголовок
- Ввожу тело
- При попытке кликнуть на Labels (из ряда Issues Pull Labels Milestones) появляется 7 вариантов
- Кликаю на question
- Появляется "Bummer, we couldn't find anything". Видимо это фильт по меткам.
А где добавление в пост?

**Comment by Alexey-T** [comment]
не знаю, не юзал

**Comment by Alexey-T** [comment]
может, это для меня.

**Comment by kvichans** [comment]
Мне каких-то прав не хватает?
Как вы метку добавили?

**Comment by Alexey-T** [comment]
я клюкнул как и вы question=оно добавилось.
