### ISSUE TITLE
OnLineChanged does not fire when a line is appended at end of file

### ISSUE THREAD

**Issue by EganSolo** [Alexey-T/ATSynEdit#171]
Alexey,

The TATStrings.OnLineChanged event fires with aChange = cLineChangeAdded when a line is inserted between two existing lines, but it does not fire when the very first line is added to the file, nor when a line is appended at the end of the file. Is there a reason for that exclusion?

I think it would be more standard if that event fired whenever a line is added, regardless of its position.

What do you think?

**Comment by Alexey-T** [comment]
No reason for it, please try to add also these cases (it's your event)

**Comment by Alexey-T** [comment]
I don't understand; what keys do you press, so that 0nChange or onChangeBlock not fired?

**Comment by EganSolo** [comment]
OnChange, not OnChangeBlock.
When I am at the last line of the file and I hit the return key. A new line is inserted but I'm not seeing the TATStrings.OnLineChanged fired.

**Comment by EganSolo** [comment]
Alexey, please close this issue. The bug was in my code. Sorry about that.
