### ISSUE TITLE
Strange log of Strings.OnChange

### ISSUE THREAD

**Issue by EganSolo** [Alexey-T/ATSynEdit#172]
Alexey,

I am almost ready to begin testing the OnChangeBlock events, but before I start that, I wanted to understand how the highlighter would behave without it so that if for whatever reason I need to disable the OnChangeBlock event, my editor would still work.

I did the following test:
I entered on line 1 (0 for the TATStrings) '///'
I entered on line 2 '//'
This led my highlighter to form a block for these two line comments. So far so good.
Then I selected both lines and hit Ctrl-X
The image shows a snapshot of that:
![twolinecomments](https://user-images.githubusercontent.com/25394601/28898514-3663b6e0-779b-11e7-9dfe-99d9a31da54b.png)
Here's what I got as my Highlighter was listening to OnLineChanged:
Event 1: CLineChangeEdited at Line 0 -- why? Why not a CLineChangeDeleted at Line 0?
Event 2: CLineChageDeleted at Line 1 -- Why not line 0? Is it because the first CLineChangeEdited is 
                                                                 supposed to be a CLineChangeDeleted?
Event 3: CLineChangeAdded  at Line 1 -- Why that event? I only have two lines, so what is being added?

I would have expected to see:

Event 1: CLineChangeDeleted at Line 0
Event 2: CLineChangeDeleted at Line 0 (since the first line is gone).

Could you please shed some light on this behavior?

Thanks

**Comment by Alexey-T** [comment]
Ctrl+X == Del key here
It is question for me too

I updated demo_editor; added listbox to log events.
Placed break point before pressing Del (Ctrl+X).
And see "CallStack". From what this break point called.

"edited" is called from TATStrings.TextDeleteRange

```
    //concat remaining parts of 1st+last lines
    Str:= '';
    if AFromX>0 then
      Str:= Copy(Lines[AFromY], 1, AFromX);
    Str:= Str + Copy(Lines[AToY], AToX+1, MaxInt);
    Lines[AFromY]:= Str; ///here
 ```

not optimal code here.

**Comment by EganSolo** [comment]
Alexey,
Please take a look at the included file. 
1. The conditional define EganSoloMod is set at the top of the at_strings_editing.inc and it is set to true. 
2. The original TextDeleteRange is preserved as is and it is part of the $Else portion of the $IfDef EganSoloMod. So to revert this method to its original simply undefine EganSoloMod.
3. That said, you will find a rewritten TextDeleteRange method that I broke into a series of procedures and functions to aid with the explanation. Once you're convinced this works then you could if you prefer bring back the code inside the body of the method.
4. My implementation respects the firing of events as you would expect them. Please read the comments within the method ExecuteCommand to better understand what I mean. 
5. The only bit of logic I am not certain about is in the procedure CleanupFinalEOL. I believe I implemented the logic as expected but since I'm not certain what its purpose is, I can't be completely sure of the attributed logic.

I tested the unit behavior lightly tonight. I plan on doing a more extensive testing tomorrow and I will let you know if I see any strange behavior. If you see any glaring error, it would be good to get that fixed.

[atstrings_editing.zip](https://github.com/Alexey-T/ATSynEdit/files/1199367/atstrings_editing.zip)

**Comment by Alexey-T** [comment]
I see the code. i cannot use it, sorry. I fear: i debugged my procedure long long time (fixes were made 2015, 2016, 2017). not sure about your procedure.

(but I'll see how to change my code for events.)

**Comment by Alexey-T** [comment]
TextDelRange optimized for (FromX=0)and(ToX=0), it fires ok events.
You suggest to optimize events for what? (FromX=0) and (ToY=Count-1) and (ToX=LineLen(ToY)) ?

**Comment by Alexey-T** [comment]
Change made
