### ISSUE TITLE
Why the choice of UTF-16 over UTF-8?

### ISSUE THREAD

**Issue by EganSolo** [Alexey-T/ATSynEdit#173]
Alexey, 
This is less of an issue and more of a question on design.
I just spent a bunch of hours understanding the Unicode implementation in FPC / Lazarus. Now that I have a much better idea of what's going on, I wanted to ask you why you chose UnicodeString (UTF-16) over String (UTF-8)?

Much of Lazarus is in UTF-8, so I've oriented my parser that way. It looks like I will have to do a UTF16ToUTF8 everytime I highlight a string. I wanted to know if that was going to be your long-term direction or if you're thinking of switching back to UTF-8? I'm specifically talking about TATStrings.Lines here. 

Thanks

**Comment by Alexey-T** [comment]
because I can a) Iterate over UnicodeString and get s[i] unicode
b) can do Copy/Delete on Unicode offsets.

**Comment by EganSolo** [comment]
You can iterate over UTF-8 pretty easily. 
The LazUtf8 and LazUnicode offer a raft of methods to manipulate utf8 strings including iterators.

I guess, it would be a significant level of effort to switch from UTF-16 to UTF-8 at this point :)

**Comment by Alexey-T** [comment]
hmm, any app, must use LazUtf8 iteration then for Lines[i], and many codes in DoCommand_* must change.

**Comment by EganSolo** [comment]
I'll first check what the performance hit is when translating from UTF-16 to UTF-8 and if that's okay with you, I'll also take a closer look at the code to see if it could be refactored to allow for both a UTF-8 and a UTF-16 implementation.

**Comment by Alexey-T** [comment]
Maybe good to see.

**Comment by EganSolo** [comment]
I've been looking deeper into utf-8 and utf-16 Alexey, going back and forth between the code in ATSynEdit and the Lazarus forums. 
Here's one thing that I'm not understanding: 
The TATStringItem stores each item as a string, which, as you know, is infact AnsiString, which is therefore unicode string encoded as utf-8. So then, my parser, instead of reading the string from TATSynEdit.Lines, could read it directly from the public variable ItemString in the TATStringITem right?

I guess, you must have decided that when it comes to string manipulation, a two-byte encoding is much easier than the variable-byte encoding in utf-8 and that's why you do everything else in UTF-16 even though the text is stored as utf-8, right?

Just trying to understand the logic, but it does take a weight off my shoulders knowing that the strings in TATStringItem are actually utf-8: I don't have to translate back and forth between utf-16 and utf-8.

**Comment by Alexey-T** [comment]
1)right, you can read utf8 string from TATStringItem w/o using Lines[ ].
2) right too.
