### ISSUE TITLE
No RemoveEditor in TATAdapterHilite

### ISSUE THREAD

**Issue by EganSolo** [Alexey-T/ATSynEdit#174]
Hey Alexey,

There's no RemoveEditor counterpart to AddEditor in TATAdapterHilite. So what's the right way to handle the event when an editor closes? I can see how the application can mediate between the editore and the highlighter but it would have been more elegant to equip TATAdapterHilite with a RemoveEditor virtual method that descendant classes implement. 

Or am I missing something?

**Comment by Alexey-T** [comment]
You need call AddEditor(nil) to remove all.

**Comment by EganSolo** [comment]
What if I close one editor? How do I capture that event?

**Comment by Alexey-T** [comment]
App must call AddEditor(nil),close any editor, then add other editors.
