### ISSUE TITLE
Strange Range behavior

### ISSUE THREAD

**Issue by EganSolo** [Alexey-T/ATSynEdit#176]
Alexey, when I create a range, the refresh of the editor happens as follows:
1. Once I detect a second comment line, I create the range. The lower portion of that range appears on the panel as the image below shows.
![range_1](https://user-images.githubusercontent.com/25394601/29701748-93058a98-8922-11e7-8b66-dde2c06b987c.png)

2. I have to move the cursor from line 2 to say line 1 for the range to show-up completely as you can see from the image below.
![range_2](https://user-images.githubusercontent.com/25394601/29701755-9e96d4e8-8922-11e7-9f49-f12c4f7175de.png)

How can I fix this?

**Comment by Alexey-T** [comment]
After added a range, you called Update?

**Comment by EganSolo** [comment]
Which update to be specific? The form or something more specific?

**Comment by Alexey-T** [comment]
It is method Update, it makes repaint, with True it also updates wrapinfo data, see wiki about Atsynedit..
