### ISSUE TITLE
Highlighting the current line

### ISSUE THREAD

**Issue by EganSolo** [Alexey-T/ATSynEdit#179]
Alexey,

What's the easiest way to get TATSynEdit to behave like the error message window in Lazarus and to highlight the line from one side of the window to the other, instead of highlighting the portion which contains text. 

If I write this:
```pascal
procedure Tfrm_TagEditor.ATSynEdit1CalcHilite(Sender: TObject;
  var AParts: TATLineParts; ALineIndex, ACharIndex, ALineLen: integer;
  var AColorAfterEol: TColor);
begin
  If aLineIndex = ATSynEdit1.Carets[0].PosY
  then with aParts[0] do
       begin
         ColorBG   := clRed;
         ColorFont := clWhite;
         aParts[0].Len := aLineLen;
       end;
end;
```
then I get this: 
![text_highlighted](https://user-images.githubusercontent.com/25394601/31580623-62449858-b10a-11e7-8ace-fec6129e8e3c.png)

but what I really want is this
![line_highlighted](https://user-images.githubusercontent.com/25394601/31580622-559a502a-b10a-11e7-8fab-835e2b5236e1.png)

**Comment by Alexey-T** [comment]
Im Alexey.

a) better to use bookmark (with red color), not hilite. `Strings.LinesBm[i]:= ....`
b) or try option OptShowFullWidthForSyntaxHilite

**Comment by Alexey-T** [comment]
ops, b) is not OK, don't work,

c) in adapter, you can set param for "color after line end" to clRed.
