### ISSUE TITLE
test msg

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATSynEdit#18]
@Stefanoko Hello, test msg

**Comment by Stefanoko** [comment]
OK. got it. 
Ran the demo version and also opened a bunch of files in it. Tried some key shortcuts on it - things I am used to from other editors - most of it worked fine. Alt up/dn to move lines (also worked on multiple lines, nice), Ctrl (Shift) navigating (selecting) words and paragraphs - stuff like that

Noticed I can mouse-wheel in edit-fields (font size, tab size etc) - but now it no longer works for some reason. Don't know what I did to make it stop working.

What I miss in all editors is "scrubbing" - the quick way of cranking up values by scrubbing over  the caption. It's available all over Adobe and media programs, but I've never seen it in text editors. You hover the mouse over the caption and the mouse pointer becomes a  <<>> double arrow that you scrub in either direction to change values. Very efficient and intuitive once you can park your eyes on the important stuff - no need to aim at the tiny up/down spin buttons.

Talking tiny - this is the biggest drawback for me, working on a hi resolution monitor, everything is way too tiny to work comfortably. The font... and option... buttons are OK, everyhing else is a strain on the eyes. Didn't find an option to crank up the interface fonts the way SynWrite allows to handle it.

Minimap works great, speedy and elegant. Micromap does not seem to be doing anything.
What's weird = dragging over the ruler - no matter if left or right - will navigate MiniMap upwards.

I'd expect a different context menu when right-clicking over the gutter or ruler, not the standard edit stuff. Clicking bookmarks into the gutter is only possible at the very outer edge, not very convenient.

Well, so much for first impressions.

**Comment by Alexey-T** [comment]
hm, UI elements aren't point here, point is "edit component". Only it. and it's menus. all elements are just testing for edit-comp. No menus for guttter- yes, no yet, in app will be. App will have menu for gutter. maybe ruler.

point is testing like "user4martin" does. he found many bugs, micro bugs

**Comment by Alexey-T** [comment]
Micromap---app will have. demo NOT makes micromap. so micromap not "done"

**Comment by Stefanoko** [comment]
Hm, not sure I can help you out here.
I need to test-run hands-on in real life applications, in practice and in
my regular workflow, doing real stuff with it.

But with the demo, I just don't know what I am supposed to do with it.
Other than playing around with the GUI. I have no real-life usage case for
it. Sorry.

**Comment by Alexey-T** [comment]
ah, got u. Real app.Then no work yet:)
