### ISSUE TITLE
Failed compiling with error DoMouseWheelHorz method unknown

### ISSUE THREAD

**Issue by vhanla** [Alexey-T/ATSynEdit#182]
Which version of FPC and Lazarus does this method have?

I can't compile it, and shows this error:

`atsynedit.pas(1033,14) Error: There is no method in an ancestor class to be overridden: "DoMouseWheelHorz(TShiftState;LongInt;POINT):Boolean;"`

I'm trying to compile it on Windows 64, FPC 3.0.0 Lazarus 1.9.0 and TCustomControl doesn't seem to have that method to override.

**Comment by Alexey-T** [comment]
It is method in Laz 1.9 trunk, not 1.8
