### ISSUE TITLE
Show a preview popup when hovering the minimap

### ISSUE THREAD

**Issue by BBasile** [Alexey-T/ATSynEdit#187]
As done in kwrite for example

**Comment by Alexey-T** [comment]
It is not present, maybe will see later about it

**Comment by Alexey-T** [comment]
Pls show some screenshots of this?

**Comment by BBasile** [comment]
The cursos was over the minimap. When i mouse move over the mimap a popup displays the code i would reach if clicking the minimap.

![screenshot_20180210_133551](https://user-images.githubusercontent.com/16154339/36062197-56101f3e-0e67-11e8-810d-ef341fac5f74.png)

It's a kind of zoom in a way.

**Comment by Alexey-T** [comment]
I can think about it later. (after IDE work is done)

**Comment by BBasile** [comment]
> after IDE work is done

You work on a IDE ? I didn't know.

**Comment by Alexey-T** [comment]
CoEdit IDE I mean

**Comment by BBasile** [comment]
You can also do it for CudaText, you know.

**Comment by Alexey-T** [comment]
@kvichans Todo

**Comment by Alexey-T** [comment]
@BBasile Started doing it. see last patch. you can see empty panel if change cInitMinimapShowTooltip to true

**Comment by BBasile** [comment]
Yeah, seems even 100% functional. That's exactly what i expected.
I've tested with one of the demo (demo_editor) which hasn't highlighting.
Is it designed so that the the tooltip text is also highlighted ?

**Comment by Alexey-T** [comment]
You can test hilite in demo-editor via Tests/ fake hilite

**Comment by BBasile** [comment]
okay i see that the tooltip has highlighting too, thanks.

**Comment by BBasile** [comment]
I suppose i can close this issue. thanks for this nice feature.
