### ISSUE TITLE
How to get the selection length ?

### ISSUE THREAD

**Issue by BBasile** [Alexey-T/ATSynEdit#189]
I'll also need to know the byte pos for the first carret. synedit had SelStart / SelEnd.

**Comment by BBasile** [comment]
For now is use `length(TextSelected)`.

**Comment by Alexey-T** [comment]
But for vert-selection you need to use SelRect...

**Comment by BBasile** [comment]
You mean because of the line ending ? Yeah indeed but the length indicated using  SynEdit has already the same problem so the feature was already bugged.

**Comment by Alexey-T** [comment]
i mean:
User can make vert-selection with alt+shift+arrows. Prop SelRect needed to calc it
