### ISSUE TITLE
LoadFromFile and SaveToFile could be virtual

### ISSUE THREAD

**Issue by BBasile** [Alexey-T/ATSynEdit#190]

**Comment by Alexey-T** [comment]
Why they are needed virtual. Def code works fully ok

**Comment by BBasile** [comment]
Real reason is that current derived class from synedit didn't have these methods. If i derive from TATSynEdit then there's a risk of shadowing. LoadFromFile is not a hot spot so the vcall shouldn't be an issue.

**Comment by Alexey-T** [comment]
"risk of shadowing"? hotspot? I dont understand

**Comment by BBasile** [comment]
- Shadowing: same declaration in base and derived. derived hides the base declaration.
- Hotspot: a part of code that's executed often and need to be more efficient.

**Comment by Alexey-T** [comment]
Now made "virtual"- OK
