### ISSUE TITLE
Adapter for SublimeText lexers?

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATSynEdit#192]
@BBasile 
If such adapter is made, you can use it in CoEdit. it must be fast. more fast than slow EControl adapter.
it is big work though...
Who can help?

Example lexer 
https://github.com/MarioRicalde/SCSS.tmbundle/tree/master/Syntaxes

**Comment by BBasile** [comment]
Don't worry, i'll write good old lexers (tokenizer) but with with a line state. For the data structure i'll use an array and probably a mechanism to avoid full rescan after each keystroke...

For CoEdit the objective is also to use the same lexer for all editing helps (such as  brace auto closing).

**Comment by BBasile** [comment]
Yeah an array or a list too. It will just prevent to write the boring array stuff. With the dynamic nature there will be indirections anyway.

**Comment by BBasile** [comment]
Maybe i'll experiment a base class using a duck type, meaning a generic highlighter that expect a set of methods in the class passed as generic parameter. Compilation error if expected methods are not there.
It's time to move on with better patterns.

**Comment by Alexey-T** [comment]
Ok, will see this hiliter.
