### ISSUE TITLE
Editor turns black, if width increases

### ISSUE THREAD

**Issue by User4martin** [Alexey-T/ATSynEdit#2]
ON w32 (vista) if I increase the width of the editor (by increasing the width of the form), when I get over aprox 140 columns, the editor  turns black

**Comment by Alexey-T** [comment]
hm.. I see 150cols, demo_load app. Ok.. Win7

**Comment by Alexey-T** [comment]
How to see it here?

**Comment by User4martin** [comment]
I build with different set of options -Criot with/without... Always happens.
fpc 2.6.4
Lazarus 1.5 trunk, 48628

I use the text, that is loaded initially (default demo text).  It happens at the same pixel width, even with a bigger font. So it is not related to the amount of text columns.

It happens when the bitmap is resized.

**Comment by Alexey-T** [comment]
better this??


procedure TATSynEdit.DoOnResize;
var
  SizeX, SizeY: integer;
begin
  inherited;

  if Assigned(FBitmap) then
  begin
    SizeX:= ((Width div cResizeBitmapStep)+1)*cResizeBitmapStep;
    SizeY:= ((Height div cResizeBitmapStep)+1)*cResizeBitmapStep;
    if (SizeX>FBitmap.Width) or (SizeY>FBitmap.Height) then
      FBitmap.SetSize(SizeX, SizeY);
  end;

  Invalidate;
end;

**Comment by User4martin** [comment]
No, but this works:


  if Assigned(FBitmap) then
  begin
    SizeX:= ((Width div cResizeBitmapStep)+1)*cResizeBitmapStep;
    SizeY:= ((Height div cResizeBitmapStep)+1)*cResizeBitmapStep;
    if (SizeX>FBitmap.Width) or (SizeY>FBitmap.Height) then begin
      FBitmap.SetSize(SizeX, SizeY);
      FBitmap.FreeImage; // <<<<<<<<<<<<<<<<<<<
    end;
  end;

I am not sure, if this should be required, or if it is a bug in TBitMap

**Comment by Alexey-T** [comment]
weird. will do.
