### ISSUE TITLE
wrap: end edge + with indent

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/ATSynEdit#20]
Оч.хорошо. Давно ждали.
Можно ли доработать перенос пробельных символов?
Идея: **переносить начиная с первого непробельного символа, попавшего за границу переноса**.

Пример. Сейчас строка
```
····abc····xyz
```
будет переноситься так
```
····abc··
    ··xyz
```
а хотелось бы так
```
····abc····
    xyz
```

**Comment by Alexey-T** [comment]
хмм, те пробелы как бы писать левее, поверх индента, не как непробелы. Зачем

**Comment by kvichans** [comment]
Опция with indent нужна только для _облегчения чтения_ - чтобы идущие подряд wrap-строки имели визуально оставались indeted. 
Моя идея имеет туже цель - чтобы сдвиговое выделение строк работало в обе стороны: малые сдвиги при wrap останутся малыми и не будут путаться с большими

**Comment by Alexey-T** [comment]
вот есть индент 8. После непробелов идут 40 пробелов и еще буквы. как это переносить. Как оно в Суб?

**Comment by kvichans** [comment]
Переносить начиная с первого непробельного символа, попавшего за границу переноса. Пусть пробелы остаются на предыдущей строке.

**Comment by Alexey-T** [comment]
хм,не понял примера- вверху- дайте пример скрина

**Comment by kvichans** [comment]
Субл поступает еще забавнее.
-  Он переносит не по символам, а по словам. 
- В ситуации, когда граница проходит по пробелам, он переносит последнее слово _перед_ границей

**Comment by Alexey-T** [comment]
хочется скрин у меня

**Comment by Alexey-T** [comment]
Суб не оставляет пробелы в начале- он по другому переносит-лучше?

**Comment by Alexey-T** [comment]
я делаю перенос если пробелы лежат на конце строки -внутри них- а Суб делает его не по пробелам..

**Comment by kvichans** [comment]
![wrap-indent](https://cloud.githubusercontent.com/assets/7419630/7220945/58b6a37e-e6e3-11e4-8048-8d808b8bb91a.JPG)

**Comment by kvichans** [comment]
Делать ли как Субл, то есть перенос по словам - это отдельная тема. Лучше или нет - еще нужно разбираться.

**Comment by kvichans** [comment]
Важно, что моя идея "не рвать сдвиги при переносах строк" реализована в Субл (по другому)

**Comment by kvichans** [comment]
Исправил пример в первом посте, чтобы прояснить идею

**Comment by Alexey-T** [comment]
А тут разве да? 
![imgsubl](https://cloud.githubusercontent.com/assets/4154978/7221085/9f5b6f50-e6e6-11e4-8ad0-8fcb4723ae20.png)

**Comment by kvichans** [comment]
Ага! Вот поэтому Син переводить на "перенос по словам" не нужно.
В вашем примере из Субл я вижу одно слово, которое уже не поддается переносу. Подозреваю, что если это первого слово разбить (вставить внутрь пробел), то на новой строке пробелов не останется - она будет начинаться со второго слова

**Comment by Alexey-T** [comment]
так пример мой- это как пример ваш- чем лучше суб?

**Comment by kvichans** [comment]
У меня мало опыта с Субл. Провел еще эксперимент, получил совсем непонятный результат:
![subl-wrap-indent](https://cloud.githubusercontent.com/assets/7419630/7221123/578690ae-e6e8-11e4-89dc-59c07b704cf9.JPG)
Значит, Субл не следует моей идее

**Comment by Alexey-T** [comment]
Да тут странно- args криво

**Comment by kvichans** [comment]
Да, про Субл я поторопился
![subl-wrap-indent-2](https://cloud.githubusercontent.com/assets/7419630/7221162/4ac5e5b2-e6e9-11e4-8bed-2aab10d19051.JPG)

**Comment by kvichans** [comment]
Добавил в первый пост формулировку идеи

**Comment by Alexey-T** [comment]
перенести можно
    ....tt.t...............
    ...............
как
    ....tt.
        t.............
        ......
разница только малая.

**Comment by Alexey-T** [comment]
это даст - в начале части строки всегда будет непробел. (невсегда). Но это мелочь

**Comment by Alexey-T** [comment]
ваш пример. "а хотелось бы так". у вас пробелы шире ширины вропа...

**Comment by Alexey-T** [comment]
в примере (1 пост) непонятно. Им. в виду, что если МОЖНО перенести что-то что даст непробел в начале строки, то делать это. 
в примере так нелзя. Можно в другом примере

    ....aaa.a...................................

**Comment by kvichans** [comment]
Да, в частном случае, когда для переноса есть только пробелы, их не переносить.
*Цель* улучшения: избавиться от состояний, когда перенесенная строка мешает понимать сдвиги соседних строк. Для Питона это критично важно, для остальных просто важно.
*Цена* улучшения: будут состояния  с (только) пробельными символами __правее__ границы переноса

**Comment by Alexey-T** [comment]
правка-не лучше??

**Comment by kvichans** [comment]
Стало лучше. 
По реализации получилось ближе к Субл, а не к моей идее.
Правильно я понял:
- Нет никаких символов **правее** границы, 
- Но возможны состояния, когда начальная строка **не достигает** границы.
![wrap-23apr](https://cloud.githubusercontent.com/assets/7419630/7291551/9a0a0a0a-e99a-11e4-9a52-2fd86858a01a.JPG)

Осталось доделать еще немного. Нужно чтобы такое поведение было привязано к настройке **with indent** (*улучшенный* перенос). Сейчас при выключении **with indent** искусственные сдвиги слева исчезают, а искусственные пропуски справа остаются.

**Comment by Alexey-T** [comment]
Прав-но поняли

**Comment by Alexey-T** [comment]
могу поправить, да

**Comment by Alexey-T** [comment]
Zip, close if ok

**Comment by kvichans** [comment]
Взял последнюю Демо. **Правые** искусственные пропуски при выключенном **with indent** остались:
![wrap-rt](https://cloud.githubusercontent.com/assets/7419630/7302064/65ca2bda-e9ef-11e4-9d55-6cdc564191ce.JPG)

**Comment by Alexey-T** [comment]
они правильны. Как ЕЩЕ перенести строку 1 на скрине?

**Comment by Alexey-T** [comment]
Кстати, есть диалог F1

**Comment by kvichans** [comment]
"Как ЕЩЕ перенести строку 1 на скрине?" У вас разве перенос по словам? Для режима **with indent**, то есть *улучшенный перенос с учетом сдвигов*, удобно переносить по словам. А без него зачем? Перенос по символам вполне ожидаем и удобен.

**Comment by Alexey-T** [comment]
по словам, всегда - перенос всегда по словам. Скрин--есть ок перенос

**Comment by Alexey-T** [comment]
"зачем"--везде так
