### ISSUE TITLE
bug with Tootip + minimap at left 

### ISSUE THREAD

**Issue by BBasile** [Alexey-T/ATSynEdit#200]
- demo_editor, set minimap to left
- put mouse over the minimap to show the tooltip
- leave the editor from the left
- move the mouse (so outside of the form)

you should see that the tooltip is updated sometimes.
It should even not be visible anymore

**Comment by Alexey-T** [comment]
I handle OnMouseLeave... what to do here ?

**Comment by BBasile** [comment]
Do you see the issue ? when leaving the form the tooltip is still there. It shouldn't.

**Comment by Alexey-T** [comment]
I don’t know how to hide tooltip here, because OnMouseLeave don’t help

**Comment by BBasile** [comment]
This is a minor issue anyway.

**Comment by BBasile** [comment]
breakpoint in MouseLeave proc shows that it's never triggered from the left, only when leaving from the right.

**Comment by BBasile** [comment]
When i set border spacing of the demo_editor main panel it's okay.
The bug was actually invalid sorry.
