### ISSUE TITLE
Gentle mousemove creates 0 length selection box

### ISSUE THREAD

**Issue by KRicketts6237** [Alexey-T/ATSynEdit#206]
I found this bug while using CudaText but tracked it down to ATSynEdit.  If one places the caret on a line, then gently moves the mouse (with the left button still pressed), but not enough to move the caret and create a visible selection box, it will create an invisible selection box that appears when one presses enter.

I am able to reliably reproduce the bug by using the mouse to plant the caret somewhere, leave the mouse button held, move the mouse enough to register a mousemove event, but not enough to start a selection box.  Press enter and it will move to a new line with a selection box from the previous caret position to the new caret position.

I tracked the bug down to a line in atsynedit.pas, around line 4276.  There is a call to DoSelect_CharRange.  If that call is wrapped in a conditional block like the one below, the problem seems to be solved.

```pascal
if (FMouseDownPnt.X <> P.x) or (FMouseDownPnt.Y <> P.y) then
begin
    DoSelect_CharRange(0, P);
end;
```

Thanks

**Comment by Alexey-T** [comment]
I confirm it because in CudaText i see

>>> =ed.get_carets()
[(23, 15, 23, 15)]

**Comment by Alexey-T** [comment]
please check the fix, seems fixed.
