### ISSUE TITLE
Undesired space when wrapping with indent

### ISSUE THREAD

**Issue by Andreas123456** [Alexey-T/ATSynEdit#21]
![undesired_space](https://cloud.githubusercontent.com/assets/12023109/7221199/46d8f568-e6e2-11e4-9407-e0e2df240877.png)

**Comment by Alexey-T** [comment]
hi. I really wrap not at edge, realy at edge-1, special, so one chr left. I really leave space at begin of wrap. ST3 also does

**Comment by Andreas123456** [comment]
Maybe ST3 also does it, but EmEditor, EditPad Pro, and HippoEdit don't.

**Comment by Alexey-T** [comment]
discussional.. what better do with space?

**Comment by Alexey-T** [comment]
Same is #20 , not sure I want changin it, it's almost ok

**Comment by Andreas123456** [comment]
I cannot read #20. And automatic translation with Google produces funny results :-)

Notepad++ does NOT have that undesired space either.

**Comment by Alexey-T** [comment]
maybe ltr... I see latr. almost ok

**Comment by Alexey-T** [comment]
Change--not bettr?

**Comment by Andreas123456** [comment]
Perfect :-)

Thank you.
