### ISSUE TITLE
'Show current line' should only show the current line

### ISSUE THREAD

**Issue by Andreas123456** [Alexey-T/ATSynEdit#22]
In the case of a long paragraph which is word-wrapped over multiple lines, 'Show current line' should only show the current line, not the whole paragraph.

**Comment by Alexey-T** [comment]
I recall -at forum. i tried to do WHEN making. but.. maybe I try again

**Comment by Alexey-T** [comment]
No promise; was hard todo to not break render spd. (also ST3)

**Comment by Alexey-T** [comment]
BETA!!Try, if ok, "CLose" btn

**Comment by Andreas123456** [comment]
Beta is okay. Thank you.
