### ISSUE TITLE
test_findmatch: error compiling project 

### ISSUE THREAD

**Issue by jcfaria** [Alexey-T/ATSynEdit#229]
Hi,

The app test_findmatch is not compiling:

```
(69)  NSkipLen:= Finder.MatchLen;
      if ANext then
(71)    NFromPos:= Finder.MatchPos 

(84)    memo3.text:= 'context:'#13+Copy(Finder.StrText, Finder.MatchPos-2, FInder.MatchLen+4);    

```
Messages:  
unit1.pas(69,21) Error: identifier idents no member "MatchLen"
unit1.pas(71,23) Error: identifier idents no member "MatchPos"
unit1.pas(84,60) Error: identifier idents no member "MatchPos"
unit1.pas(84,79) Error: identifier idents no member "MatchLen"

Best,
J.C.Faria

**Comment by Alexey-T** [comment]
Thanks..
