### ISSUE TITLE
Column not kept

### ISSUE THREAD

**Issue by Andreas123456** [Alexey-T/ATSynEdit#23]
To reproduce the issue, follow these steps:

- Turn off the option 'caret after eol'.

- Type the following text:

abcdefg
hij
klmnopqrst

- Place the cursor onto the letter q.

- Press two times the 'cursor up" key.

Expected result: The cursor will be on the letter g.
Actual result: The cursor will be on the letter d.

**Comment by Alexey-T** [comment]
todo, OK

**Comment by Alexey-T** [comment]
for "[x]Nav in wrap-line"OK now. Beta. (For oth case not yet)

**Comment by Alexey-T** [comment]
"Close" if Ok
