### ISSUE TITLE
Clarification on OnChange vs OnChangeModified

### ISSUE THREAD

**Issue by ikelaiah** [Alexey-T/ATSynEdit#236]
Hi,

Taken the following excerpt from `demo_editor`.

```

  ed.OnChange:= @EditChanged;
  ed.OnChangeModified:=@EditChangeModified;  

```

I looked into the source code but still unsure the difference between these two events.
Could you clarify? Thanks.

**Comment by Alexey-T** [comment]
OnChangeMidified - fired when Modified was changed (ie more rarely than OnChange)

**Comment by ikelaiah** [comment]
Thanks. That means, I should use `OnChange` to add `*` on the caption to indicate that document has been changed. Am I correct?

**Comment by Alexey-T** [comment]
Nope, use OnChangeModified to show and hide the star

**Comment by Alexey-T** [comment]
You can use single ObChange too ( ignoring ObChangeModified)

**Comment by Alexey-T** [comment]
'Modified" changed from False to True: OnChangeModified fires.
'Modified' changed from True to False (on Undo): too.
