### ISSUE TITLE
How to set Emoji popup position on Win10

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATSynEdit#238]
https://thenextweb.com/microsoft/2017/06/09/windows-10-now-emoji-shorcut-time/
this popup shows at random position.
we need it near the caret.
how to do it?

@rasberryrabbit @vhanla

**Comment by Alexey-T** [comment]
I got a reply
```


While I can't provide you with any code snippets right of the bat, the function you are looking for is probably ImmSetCandidateWindow

The emoji panel acts as an IME and bears a very strong resemblance to parts of Microsofts chine IME.
```
how to use it?

**Comment by rasberryrabbit** [comment]
Message event handler is unknown, application cannot catch it at openning window.
