### ISSUE TITLE
Does not paint line after 400 visible chars

### ISSUE THREAD

**Issue by User4martin** [Alexey-T/ATSynEdit#24]
I have a very wide screen/desktop (multi monitor).
If I stretch the editor over the entire width of my screen, I can (with a small font) display about 1000 chars in a line WITHOUT scrolling. (they are all visible at the same time).

Or rather I could.

ATSynEdit only paints 400 chars of the line, and then an empty white space.

**Comment by Alexey-T** [comment]
What if u change

      cMaxCharsForOutput = 400;

**Comment by User4martin** [comment]
Doesnt work, There is at least also 
  TATLineParts = array[0..400] of TATLinePart;

If I change both, then it works.

IMHO a hardcoded limit is bad, he array could be a dynamic array (allocated on resize), and the size cMaxCharsForOutput could also be calculated.

**Comment by Alexey-T** [comment]
-hardcoded limit is bad, he array could be a dynamic
yep. I see not easy to make dyn-ar. DoCalcLineHilite needs rework if dyn. so i dont do it. realloc will be slower

**Comment by Alexey-T** [comment]
changed: 1000
