### ISSUE TITLE
ed.OnChangeModified fires once only

### ISSUE THREAD

**Issue by ikelaiah** [Alexey-T/ATSynEdit#240]
Hi,

I've been trying to show * when document modified, but no avail. 

The following line...

```
ed.OnChangeModified:=@EditChangeModified;
```

in my program only fires once during the lifetime of the program.

When I launch, then modify, * appears.
Open a file
Modify, nothing happens. * does not appear.

I must be missing something. Could you help?

**Comment by Alexey-T** [comment]
On file-opening, you must clear Modified state. does it help?

**Comment by ikelaiah** [comment]
@Alexey-T 

Ah! The solution is too obvious! Thank you.

Yes, clearing the Modified state using `self.SynEditor.Modified := False; ` does work!

Thanks for this editor, thanks for maintaining it, you saved me countless of hours!!!
