### ISSUE TITLE
HTML syntax highlight - Font weight changes when caret moves into it

### ISSUE THREAD

**Issue by ikelaiah** [Alexey-T/ATSynEdit#241]
![2019-06-15 changing caret size - AT ](https://user-images.githubusercontent.com/32469901/59536382-ea18a380-8f36-11e9-8b4b-64938a8d18e8.gif)

Hi,

Managed to get the HTML syntax highlighter to work. I noticed when I move the caret inside <> the font weight changes. Is this expected behaviour?

Thank you.

**Comment by Alexey-T** [comment]
- get the last lexer from CudaText
- turn off dynamic highlight (caret depending) in adapter prop.

**Comment by ikelaiah** [comment]
@Alexey-T 

Using `adapter.DynamicHiliteEnabled:=False; ` does not change weight. Nice one.
I will get the latest lexer from CudaText. 

Many thanks.

**Comment by Alexey-T** [comment]
Can I reproduce this in CudaText, how?

**Comment by Alexey-T** [comment]
Ah, it’s solved? Ok

**Comment by ikelaiah** [comment]
@Alexey-T 

Resolved, without using Cuda's lexer. Only using `adapter.DynamicHiliteEnabled:=False;`

Thank you.
