### ISSUE TITLE
How to donate to this project?

### ISSUE THREAD

**Issue by ikelaiah** [Alexey-T/ATSynEdit#242]
Hi,

How do I donate to this project? 
Thanks.

**Comment by Alexey-T** [comment]
Pls see: http://uvviewsoft.com/donate.htm

**Comment by ikelaiah** [comment]
Hi,

It didn't go through. See the error screen attached. I used my VISA.
I'll buy some licenses for Universal Viewers, is that ok?

![2019-06-19 11_41_32-Yandex Money](https://user-images.githubusercontent.com/32469901/59730919-815b5f00-9287-11e9-8439-4ef6630a8f23.png)

**Comment by Alexey-T** [comment]
Yes, it is fully correct too.

**Comment by ikelaiah** [comment]
I'll try to transfer money to Yandex Money. if it fails again, 
I will purchase Universal Viewers instead to donate to this project.

Again, many thanks.

**Comment by Alexey-T** [comment]
Thanks

**Comment by ikelaiah** [comment]
I've purchased a license of Universal Viewers. Thanks.

**Comment by Alexey-T** [comment]
Got it, thank you!
