### ISSUE TITLE
Editor Example Crashes When Clicking on Empty Minimap

### ISSUE THREAD

**Issue by ikelaiah** [Alexey-T/ATSynEdit#243]
I am using minimap in my project. When the text is empty and i click on the empty minimap, it crashes.

This behaviour is also in the Editor demo. I provided a screencast.

![2019-06-18 crashes when click on empty minimap - AT (cropped)](https://user-images.githubusercontent.com/32469901/59643524-610aa200-91ac-11e9-91ba-8e0eeebea61e.gif)

The error is

> Project Demo raised eception class `External: SIGFPE`
> In file `atsynedit.pas` at line 2977`

The error leads to the following line;

```
Result:= Int64(FScrollVert.NPosLast) * NScrollPos div NScrollMax;
```

Unfortunately, I don't quite understand `function TATSynEdit.GetMinimap_DraggedPosToWrapIndex(APosY: integer): integer;`

Could you help?

**Comment by Alexey-T** [comment]
Division by zero
