### ISSUE TITLE
Errormessage cannot stream chosen component

### ISSUE THREAD

**Issue by RuedigerD** [Alexey-T/ATSynEdit#246]
Hi, I'm on Lazarus 2.06 win64. ATSynedit insstalled fine, IDE recompiled without any issues. 
All other components on the ATsection work fine. If I try to put an ATSynedit on any form, I get errormessage "cannot stream chosen component".

Any hints?
Thanks in advance
Ruediger
![error_atsynedit](https://user-images.githubusercontent.com/61328473/75060600-66f51780-54df-11ea-9a37-ab3226d8391b.jpg)

**Comment by Alexey-T** [comment]
I see the same error on Linux x64, but don't know where it's raised...

**Comment by Alexey-T** [comment]
Fixed, to fix it I hide the PopupNnnnn props to the public section, from published
