### ISSUE TITLE
No CRLF support inside LineInsert/LineBlockInsert

### ISSUE THREAD

**Issue by iandarken** [Alexey-T/ATSynEdit#248]
If Line in string/TStringList contains LineEnding, during LineInsert/LineBlockInsert it simply puts CRLF sym instead of actual new line without option to change this behaviour

**Comment by Alexey-T** [comment]
I supposed that user makes StringList from a string, then calls LineInsertStrings().

**Comment by iandarken** [comment]
That changes a little - since TATStrings also keeps string with CRLFs intact.
My current w/o is to TStringList.AddText(s) that parses CRLFs in s into separate lines in TStringList and then adding this TStringList to LineBlockInsert

**Comment by Alexey-T** [comment]
procedure TATStrings.LoadFromString(const AText: atString);

here you can load string with CRLF into ATStrings, then pass ATStrings to LineInsertStrings. OK?

**Comment by iandarken** [comment]
Ah, yes, that fits!
