### ISSUE TITLE
chars overlapped on long text line when length > 500

### ISSUE THREAD

**Issue by uvwx413** [Alexey-T/ATSynEdit#259]
Easten Asia Characters(Full Char with 2 alpha width) will be overlapped each other when the text line over 500 chars length.
and  the same  case  is in CudaText.

If Change 
       OptMaxLineLenForAccurateCharWidths: integer = 500;      // ATStringProc.pas line 83
to
       OptMaxLineLenForAccurateCharWidths: integer = 5000;    
everything is right ( while line length < 5000 Chars)

So, I suggest  to add a property,  optMaxLineLenForAccurateCharWidths  to ATSynEdit control,  then user can change it in IDE or at RTM.

ATSynEdit is a PERFECT control ! 
It is so fast when  loading big files (faster than famous SynEdit).  Thanks！

**Comment by uvwx413** [comment]
![image](https://user-images.githubusercontent.com/72081475/101241303-c7340d80-372f-11eb-86b4-77f4b8e2d1bb.png)

**Comment by Alexey-T** [comment]
CudaText has option for it,
plugin Option Editor:
![Screenshot from 2020-12-22 20-40-28](https://user-images.githubusercontent.com/4154978/102917271-fa97cb80-4495-11eb-93a5-e7294749bd9a.png)

atsynedit has option too

**Comment by Alexey-T** [comment]
better to have 'global option' for this. than to have a property. global option is easy to use.
