### ISSUE TITLE
redo always does all undo

### ISSUE THREAD

**Issue by User4martin** [Alexey-T/ATSynEdit#26]
With group undo:

if you write text, go to new place, write text, go to new place, write text, go to new place, write text....

Then you can press undo, and it undoes one piece of text at a time (correct). 

So undo 3 or 4 times. Now if you Redo, it will redo all, and al the undo become a single undo too, instead of being 3 or 4.

**Comment by Alexey-T** [comment]
It's MOST hard part. maybe later i see

**Comment by Alexey-T** [comment]
Is okey, a fix.
