### ISSUE TITLE
Can't compile package atsynedit_package.lpk

### ISSUE THREAD

**Issue by zoltanleo** [Alexey-T/ATSynEdit#260]
Hi Alex.

When I try to compile this package I get several errorы like:
> atsynedit_regexpr.pas(5311,18) Error: Operation "+" not supported for types "PWideChar" and "PWideChar"

fpc -r46803, laz  63874M Win 10 x64

**Comment by Alexey-T** [comment]
it is known FPC 3.3 trunk bug. I reported it to FPC issue tracker.

**Comment by Alexey-T** [comment]
FPC dev wrote that its fixed! 
pls check on new FPC version
https://bugs.freepascal.org/view.php?id=37621

and write here is it solved?

**Comment by zoltanleo** [comment]
It's OK. Thank a lot.

But... When I run any demo now I get error

> Project Demo raised exception class 'External: SIGSEGV'.
> 
>  In file 'atsynedit_regexpr.pas' at line 4629:
> offset := PRENextOff(AlignToPtr(p + REOpSz))^; // ###0.933 inlined NEXT

Any idea?

**Comment by Alexey-T** [comment]
yes, it is also FPC trunk bug. I also reported it in mantis. i use FPC 3.2 release for Cudatext.

**Comment by zoltanleo** [comment]
OK. I will wait for the fix in the next revision of the trunk

**Comment by Alexey-T** [comment]
please bump the dev's for FPC:
https://bugs.freepascal.org/view.php?id=37625
