### ISSUE TITLE
Error: Identifier not found "BitmapResizeBySteps"

### ISSUE THREAD

**Issue by fllsilva** [Alexey-T/ATSynEdit#268]
I recently updated my version and can no longer compile due to the "Identifier not found BitmapResizeBySteps" error.

atsynedit.pas(4934,11)

**Comment by Alexey-T** [comment]
ATFlatControls is required, did you update it from Github?

**Comment by fllsilva** [comment]
No, I updated via the Lazarus Online Package Manager.

ATFlatControls V2.0.0.0
ATSynEdit V2.1.0.0

It must be missing to update the Lazarus repository then.

**Comment by Alexey-T** [comment]
I will update packages there, soon
