### ISSUE TITLE
First character in wrapped line unreachable

### ISSUE THREAD

**Issue by Andreas123456** [Alexey-T/ATSynEdit#27]
In a wrapped paragraph, it is impossilbe to reach the first character in the second line by means of the 'cursor left' and 'cursor right' keys.

**Comment by kvichans** [comment]
How to repeat? What's state of options aroud "wrap"?

**Comment by Andreas123456** [comment]
![unreachable](https://cloud.githubusercontent.com/assets/12023109/7252166/adba0582-e832-11e4-86ca-492527e43923.png)

**Comment by kvichans** [comment]
Where is caret when "o unrechable"? 
I repeat and view caret at the last pos of __prev__ line. It's true! 
I can select "o" -- thus it's reachable.

**Comment by Andreas123456** [comment]
You are right: The caret is at the last pos of prev line and the "o" is reachable. So the title of my bug report is wrong.

But nevertheless there is a problem. The caret should not be at the last pos of prev line. Instead, it should be in the first pos of the second line (directly before the "o").

**Comment by Alexey-T** [comment]
-a problem which need to be corrected.
nope: ST3 does it, i make it like it- special- on prev line

**Comment by Andreas123456** [comment]
I still regard this as a bug or at least as very confusing, because it's against all usual conventions. SynWrite and ALL other editors I know (except ST) do it correctly. It's better to follow the usual conventions.

**Comment by Alexey-T** [comment]
okay.Will be optn

**Comment by Alexey-T** [comment]
ZIP: OK? close if ok

**Comment by Andreas123456** [comment]
It's ok now. Thank you.
