### ISSUE TITLE
Bookmarks Event

### ISSUE THREAD

**Issue by rayhester** [Alexey-T/ATSynEdit#278]
Hi Alexey

Would it be possible to add an event to be triggered when the list of bookmarks changes
so that menu items and buttons could be enabled/disabled according to the list count.

I see that CudaText bookmarks menu items are always enabled even when there are no bookmarks placed, so I 
guess I am not overlooking something.

(With CudaText, if there are no bookmarks and the menu item 'Go to next bookmark' is selected the app hangs, at least on
my Windows 10.)

Thanks for your excellent components!

**Comment by Alexey-T** [comment]
I added OnChangeBookmarks, pls test that all changes fire that event.
