### ISSUE TITLE
Access Bookmarks Data

### ISSUE THREAD

**Issue by rayhester** [Alexey-T/ATSynEdit#279]
Hello Alexey

Thanks for so quickly adding the 'OnChangeBookmarks' event, it does exactly what I wanted.

Has something else changed?

Using Strings.Bookmarks.Items[i].Data.LineNum to add all bookmarks to a TListView, which
worked before, now gives:

	Error: identifier idents no member "Items"

Is there another way to access an item's data?

I am on Windows 10 and have been using version 2.3.0.0 via the Online Package Manager
until I downloaded the latest source to test the new bookmarks event.

**Comment by Alexey-T** [comment]
I cannnot recall when we had 'Items'. now we have--
```
  TATBookmarks = class
  private
    FList: TATBookmarkItems;
    function GetItemPtr(N: integer): PATBookmarkItem;
  public
    constructor Create; virtual;
    destructor Destroy; override;
    procedure Clear;
    procedure Delete(N: integer);
    procedure DeleteForLine(ALine: integer);
    function DeleteByTag(const ATag: Int64): boolean;
    function Count: integer;
    function IsIndexValid(N: integer): boolean;
    property ItemPtr[N: integer]: PATBookmarkItem read GetItemPtr; default;
    procedure Add(const AData: TATBookmarkData);
    function Find(ALineNum: integer): integer;
    procedure DeleteDups;
    procedure Update(AChange: TATLineChangeKind; ALine, AItemCount, ALineCount: integer);
  end;

```
