### ISSUE TITLE
Press LEFT for move caret to end of prev line

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/ATSynEdit#28]
Сейчас каретка не перемещается с первой позиции второй строки на последнюю позицию первой строки при нажатии ВЛЕВО. Опции для такого поведения не нашел. Это будет?

**Comment by Alexey-T** [comment]
Как и син. зависит от caret-after-eol..

**Comment by Alexey-T** [comment]
"Close" if OK pls

**Comment by kvichans** [comment]
Вижу у себя
[x]caret atfer eol
но попасть с начала второй строки в конец первой не могу.
Что-то еще?

**Comment by Alexey-T** [comment]
Выкл эту опцию, тогда можно, нет?

**Comment by Alexey-T** [comment]
Что предлагаете, делать опцию чтоь всегда перейти на пред строку? а такая опция есть где-то, не видел

**Comment by kvichans** [comment]
Как это в Сине? У меня в Син каретка не бывает за за eol (это наверно **[x]Keep caret in text**), но ВЛЕВО перемещает ее на конец пред.строки

**Comment by Alexey-T** [comment]
так в Сине. в сине опция keep-car-in-text, то же что тут caret-after-eol OFF

**Comment by kvichans** [comment]
Да, неправильно понимал смыл **[x]caret atfer eol**. Выключил опцию и стало хорошо

**Comment by Alexey-T** [comment]
Ну вот
