### ISSUE TITLE
Error using clipboard

### ISSUE THREAD

**Issue by aducom** [Alexey-T/ATSynEdit#287]
I'm running Lazarus 2.0.12 and i get an error message using ctrl-c 
![image](https://user-images.githubusercontent.com/5610893/132658545-a12f17ec-876b-455b-8eb3-ee88b9580e7f.png)

**Comment by aducom** [comment]
actually, I doubt if this is a component issue. While debugging I found the following where the line was commented out:
(in lclintf.inc)

function ClipboardRegisterFormat(const AMimeType: string): TClipboardFormat;
begin
  Result := WidgetSet.ClipboardRegisterFormat(AMimeType);

**Comment by Alexey-T** [comment]
Some do you have the error on clean Lazarus release?

**Comment by aducom** [comment]
Appearantly. I never touched that code afaik.

**Comment by aducom** [comment]
Well, everything looks like is working, so I close this thread. If anyone runs into this issue, uncomment the line documented above.
