### ISSUE TITLE
Editor hangs with fold

### ISSUE THREAD

**Issue by User4martin** [Alexey-T/ATSynEdit#29]
- Run the demo.
- Select fold from menu
  (lines 11 to 20 are folded)
- left click the line-number-part of the gutter on line 11 (in front of the fold marker), 

Normally this should select the line. But the editor just stops to respond. It goes into an endless loop.

**Comment by Alexey-T** [comment]
IsPosCollapsed/ fixd/ don't paint caret in [..]
