### ISSUE TITLE
Build failure on (32bit) Haiku

### ISSUE THREAD

**Issue by Begasus** [Alexey-T/ATSynEdit#291]
Trying to get CudaText to build there results in an error for ATSynEdit:

`/Opslag/CudaText_up/src/ATSynEdit/atsynedit/atsynedit.pas(8312,9) Error: (5000) Identifier not found "IM_Context_Set_Cursor_Pos"`

Running with: `./cudaup.sh -g -m -l /boot/system/non-packaged/bin/fpcupdeluxe/lazarus`

fpc and lazarus build with fpcupdeluxe (trunk from a few weeks ago)

**Comment by Alexey-T** [comment]
That identifier is from the newer Lazarus:

```
C:\fpcupdeluxe\fpcupdeluxe\lazarus\components\synedit\lazsyngtk2imm.pas
components\synedit\lazsyngtk2imm.pas (45,7) IM_Context_Set_Cursor_Pos(FriendEdit.CaretXPix,FriendEdit.CaretYPix+FriendEdit.L...
C:\fpcupdeluxe\fpcupdeluxe\lazarus\lcl\interfaces\gtk2\gtk2globals.pp
lcl\interfaces\gtk2\gtk2globals.pp (74,11) procedure IM_Context_Set_Cursor_Pos(X, Y: gint);
lcl\interfaces\gtk2\gtk2globals.pp (438,11) procedure IM_Context_Set_Cursor_Pos(X, Y: gint);
```

**Comment by Alexey-T** [comment]
You can update Lazarus, or just comment this IFDEF
```

{$ifdef LCLGTK2}
  {$if (LCL_FULLVERSION >= 2030000)}
    {$define GTK2_IME_CODE} ////comment this
  {$endif}
{$endif}
```
in atsynedit.pas.

**Comment by Alexey-T** [comment]
But you make the CudaText on HAIKU, so you must activate widgetset QT5!! then that line
```
{$ifdef LCLGTK2}
  {$if (LCL_FULLVERSION >= 2030000)}
    {$define GTK2_IME_CODE} ////comment this
  {$endif}
{$endif}
```

will be deactivated!

**Comment by Begasus** [comment]
> cudaUp script has the param to activate qt5!

Looked into the script but can't seem to find it?

**Comment by Alexey-T** [comment]
```
Usage: $(basename $0) [option...]
Options:
  -g  --get                  download packages
  -p  --packs                install packages to Lazarus
  -m  --make                 compile CudaText
  -l  --lazdir <directiory>  set Lazarus directory
  -o  --os <system>          set target OS (win32/win64/linux/freebsd/darwin/solaris)
  -c  --cpu <arch>           set target CPU (i386/x86_64/arm)
  -w  --ws <widgetset>       override WidgetSet (gtk2/gtk3/qt/qt5/cocoa)
      --clean                delete temp Free Pascal folders (src/*/*/lib/*-*)
  -h  --help                 show this message
"
```
so you must set param "--ws".

**Comment by Begasus** [comment]
Bumps head ;) running atm with `-w qt`

**Comment by Begasus** [comment]
Error while linking: `cannot find -lQt4Pas` (we've got system -lQt5Pas)?

**Comment by Alexey-T** [comment]
`-w qt5` - Qt _5_.

**Comment by Begasus** [comment]
Thanks! Running: 

`./cudaup.sh -g -m -w qt5 - Qt 5 -l /boot/system/non-packaged/bin/fpcupdeluxe/lazarus`

Resulted in success! :+1: 

![CudaText](https://user-images.githubusercontent.com/16057090/146737083-433120f1-ab41-451b-a228-b1d54c7e13e6.png)

**Comment by Alexey-T** [comment]
`- Qt 5` was not needed, it was my text comment

so
`./cudaup.sh -g -m -w qt5 -l /boot/system/non-packaged/bin/fpcupdeluxe/lazarus`

**Comment by Alexey-T** [comment]
@Begasus Can you tell me what is the default MONOspaces font on Haiku? i will hard code it as default.

**Comment by Alexey-T** [comment]
I have the hardcoded font names for Haiku -

proc_globdata.pas
```
const
  AppDefaultEdFont: string = '';
  AppDefaultEdFonts: array[0..2] of string =
    {$ifdef windows}
    ('Consolas', 'Courier New', 'Courier');
    {$else}
      {$ifdef darwin}
      ('Monaco', 'Liberation Mono', 'DejaVu Sans Mono');
      {$else}
        {$ifdef haiku}
        ('Noto', 'Monoid Nerd', '');
        {$else}
        ('DejaVu Sans Mono', 'Liberation Mono', 'Courier New');
        {$endif}
      {$endif}
    {$endif}
               
```
Do you miss fonts

- Noto
- Monoid Nerd ?

**Comment by Begasus** [comment]
Noto is installed, default it's using `Noto Sans Display`, changed that to `Noto Sans Mono`

**Comment by Alexey-T** [comment]
made the patch linked above this comment. it must fix the default font?

**Comment by Begasus** [comment]
I'm guessing default font is set to `Noto Sans Display` (thought is was Mono), changed back to Noto Sans Display (only enlarged  the font), cp'd 2 directories into ~/config/settings/cudatext to get the toolbar icons and a missing py folder on CudaText launch, also played a bit with the themes ;)

![Cuda-Text-font](https://user-images.githubusercontent.com/16057090/146746057-285b3b58-107a-444e-b69b-05f2e7b72dfc.png)

**Comment by Begasus** [comment]
> 

Works fine with it, thanks!

**Comment by Alexey-T** [comment]
Looks good.
On the next compliation of Cud, the default font must be detected as 'Noto Sans Mono'.

**Comment by Begasus** [comment]
> On the next compliation of Cud, the default font must be detected as 'Noto Sans Mono'.

It did, (renamed the user.json file to check) :+1:

**Comment by Begasus** [comment]
@Alexey-T is it possible to set the font size to `12` in the source too?

**Comment by Alexey-T** [comment]
Added patch to set font size to 12 
(link above this comment)

**Comment by Begasus** [comment]
Thanks, checking ...

**Comment by Begasus** [comment]
Hi @Alexey-T I'm trying to bring CudaText for Haiku uptodate, but running the mentioned command above not gives me a: lazbuild: Could not resolve symbol 'libiconv_open
I'm unsure if this is an issue with lazarus (bumped libqt5pas and fpcupdeluxe earlier today), but I've seen it before in other attemps. Searching the web doesn't really helped so far. :/

**Comment by Alexey-T** [comment]
Pls move this issue to CudaText repo. but I dont know the reason! sorry
