### ISSUE TITLE
The Blue HourGlass

### ISSUE THREAD

**Issue by vertikalm** [Alexey-T/ATSynEdit#292]
After updating the ATSynEdit package yesterday, a blue hourglass (really big), appears for an instant before loading text in the editor (inside of the control). Actually, he would swear he had not seen him before.

Is this a novelty of Atsynedit?

I have also observed that the package says depend on a specific version of BGrabitmap, I do not know if when recompiling the IDE, my version of BGRA suffered a Upgrade or a Downgrade. Is this recommendation from the BGRA version pointing to a modern version?

Apart from these two changes, nothing has changed in my system. I really have a curiosity about this hourglass.

**Comment by Alexey-T** [comment]
Hourglass is shown on loading from file / stream. Maybe I need to disable it for small files, eg < 50k.

**Comment by Alexey-T** [comment]
BgraBitmap - just install the last github version or release. What is bad ?

**Comment by vertikalm** [comment]
Hourglass: It's easy to customize this?
BGRA: It's a question rather about online Package Manager, I do not know if you force the installation of an older library than I have installed, if a package requires it with anterior version. But no problem, all right.

**Comment by Alexey-T** [comment]
hourglass:

- I made small fix to not show hourglass for pos=0. in github.
- const is in atsynedit_options, TATEditorOptions.ProgressLoadChars

**Comment by Alexey-T** [comment]
> I do not know if you force the installation of an older library than I have installed,

no, I do not force anything. my LPK version is from the air - I don't know about versions

**Comment by vertikalm** [comment]
All perfect thanks.

**Comment by Alexey-T** [comment]
what kind of project are you doiing? no info in the Github...

**Comment by vertikalm** [comment]
At the moment none, only testing components. I really entered Github for your recommendation in the Lazarus forum, it is also related issues related to ATSYnedit.
Maybe it's a good opportunity to learn git.
Thanks for everything.
