### ISSUE TITLE
CanvasPaintRoundedCorners missing

### ISSUE THREAD

**Issue by yonist** [Alexey-T/ATSynEdit#293]
When trying to install the latest version (2022.8.04) I get the following error:

atsynedit.pas(3271,5) Error: Identifier not found "CanvasPaintRoundedCorners"

I'm using Lazarus 2.0.10 is it supported?

Thanks

**Comment by Alexey-T** [comment]
you have too old ATFlatControls, so update it - better from GitHub (not sure that OnlinePackageManager has ok version).
