### ISSUE TITLE
Switching from ATSynEdit_RegExpr to RegExpr will not compile

### ISSUE THREAD

**Issue by yonist** [Alexey-T/ATSynEdit#294]
When compiling with the RegExpr unit I get the following error:

atsynedit.pas Error: identifier idents no member "IsCompiled" 

I'm using the release from 2022.08.04

**Comment by Alexey-T** [comment]
You need newer FPC version, 3.2.3 or later.

**Comment by yonist** [comment]
True, I'm using 3.2.0

**Comment by Alexey-T** [comment]
I will see how to adapt it for older FPC

**Comment by Alexey-T** [comment]
fixed now, pls test again.

**Comment by yonist** [comment]
It is working, thanks.
