### ISSUE TITLE
Console mode

### ISSUE THREAD

**Issue by yonist** [Alexey-T/ATSynEdit#297]
Hi, 

I created a new mode that make ATSynEdit to behave like a command line console (this is something that I need for a project I'm working on)

First ATSynEdit is a great, The code is very clear and it really easy to navigate and change

Second, you can find my fork here https://github.com/yonist/ATSynEdit, I also created a new demo in https://github.com/yonist/ATSynEdit/tree/master/app/demo_console (it already contains a compiled exe file for convenience)

Third while it works, it still has issues with text selecting. And I'll probably architect the code differently

Last, I do have some questions regarding ATSynEdit functionality and internal design. Is it OK to ask them here? 

Thanks,

**Comment by Alexey-T** [comment]
> I do have some questions regarding ATSynEdit functionality and internal design. Is it OK to ask them here?

yes, in new issues. welcome.

**Comment by Alexey-T** [comment]
I don't understand why don't you move all 'console code' to a user app level. why to embed this rarely needed code to core!

**Comment by yonist** [comment]
The main problem is controlling the caret position, it can only be on the last line but it cannot move before the prompt text. modeling that into the app level proved to be very difficult as there are some corner cases were the proper behavior is achieved only if the constrained are checked both before and after ATSynEdit processed the user input.

**Comment by Alexey-T** [comment]
then we must add smthing like OnCanChangeCaret. I will add it.

**Comment by yonist** [comment]
I'll give you 2 examples to consider: 
1. when the user press 'home' the caret needs to move to the beginning of the line before the prompt, but that if only the control can accept input because it can be in blocking mode. 
2. when the user press 'ctrl+c' if there is a selection, the text should be copied otherwise it should be processed by the application

**Comment by Alexey-T** [comment]
we have OnChangeCaretPos, why don't you use it and correct the caret pos?

Carets[0].PosX:= ... 
Carets[0].PosY:= ...

**Comment by yonist** [comment]
Because it caused flickering in my testing:  The caret is first move to the incorrect position and then back to the correct one. Simply put this is ugly and bad user experience

**Comment by Alexey-T** [comment]
just added OnPaint. in Git.
pls try to change caret pos in OnPaint. I see that Enter-key still flickers, is it bad for you?

**Comment by Alexey-T** [comment]
just added OnCalcCaretsCoords.
it must be enough - change caret pos there (don't set in OnPaint and other places).
i dont see any flickring with it.

**Comment by yonist** [comment]
Thanks, I'll check it (converting the code is few hours work I'll do it over the weekend)

**Comment by yonist** [comment]
How can I hide the caret while still have a focus on the control? 

Currently FCaretShowEnabled is not exposed, I need to be able to control its state (a user may enter a command which runs in async mode, rendering only a progress bar, and the user can still press "ctrl+c"  to cancel it)

**Comment by Alexey-T** [comment]
>How can I hide the caret 

Ed.Carets.Clear;

**Comment by Alexey-T** [comment]
Another way: change Ed.CaretShapeNormal (and other 2 CaretShape*).

**Comment by Alexey-T** [comment]
>Also when I add line the editor doesn't render the new line (Strings.LineAdd) . I tried working with update(), invalidate(), Begin/End Editing, Begin/End Update and nothing...

Ed.UpdateWrapInfo(). without WrapInfo update , all is bad.

**Comment by yonist** [comment]
You mean like that?

```
FEditor.Strings.LineAdd('my text');
FEditor.UpdateWrapInfo(true);  
```
I tried all sort of combinations and it doesn't work...

**Comment by Alexey-T** [comment]
on linux, I added demo with a button. OnClick of btn
```
procedure TForm1.Button1Click(Sender: TObject);
begin
  ed.strings.LineAdd('eeeee');
  ed.Update(true);
end;           
```
it works.
even without heavy fix:
```
procedure TForm1.Button1Click(Sender: TObject);
begin
  ed.strings.LineAdd('eeeee');

  ed.UpdateWrapInfo(true, false);

  ed.Update(true);
end;           
```

**Comment by yonist** [comment]
On Windows this works too:
```
FEditor.Strings.LineAdd(FPrompt);
FEditor.Update(true);
```
Thanks!

**Comment by yonist** [comment]
hi, it seems that OnCalcCaretsCoords event is being called twice for each key press (I debugged it and it is not related to my own code). As you can see in the attached screenshot. Is that an expected behavior?  

![twice](https://user-images.githubusercontent.com/499992/193199041-bc703a4d-d581-463a-bc5e-efc7e3c7f19a.png)

**Comment by Alexey-T** [comment]
as expected. because TATSynEdit.UpdateCarersCoords is called 2 times in DoCommandResults.

**Comment by yonist** [comment]
Sure! I have just downloaded it and I will start using it today.

**Comment by yonist** [comment]
regarding OnCalcCaretsCoords being called twice... I'm confused. The code path looks like this:

TATSynEdit.DoPaintAll -> UpdateCaretsCoords -> FOnCalcCaretsCoords(self)

It looks like the control is being painted twice for each keypress.

**Comment by Alexey-T** [comment]
i think DoPaintAll is called once, but it calls UpdateCaretsCoords 2 or 3 times.

**Comment by yonist** [comment]
You are right 

For every key press UpdateCaretsCoords is being called from DoCommandResults and DoPaintAll. 

Just for testing I removed the call from DoCommandResults  and all seems to be working for my use case...

**Comment by Alexey-T** [comment]
Seems it was needed for CudaText plugins. plugins can call N times Ed.DoCommand() so each DoCommand must call DoCommandResults so each must call UpdateCaretsCoords (otherwise we see bugs with caret moving if some command scrolls the editor). DoPaintAll's call may be unneeded(??)

**Comment by Alexey-T** [comment]
ah. DoPaintAll's call is needed too, because editor can be scrolled by mouse or text can be selected by mouse (DoCommand is not called here).

**Comment by yonist** [comment]
Yes, it also needed after Strings.LineAdd, as it doesn't update the cursor location (again not passing through DoCommand )

**Comment by yonist** [comment]
Is there an elegant way to do put spacing between the beginning of the text  and the control edge?

![image](https://user-images.githubusercontent.com/499992/193416708-f8b036ec-cf86-48d8-b54c-12b18d09b601.png)

**Comment by Alexey-T** [comment]
yes. Turn on Gutter visible. then in Gutter bands, turn off all bands except only 'separator' band, and set this band's width.

how to do it? see my demo_editor which has Options dlg.

**Comment by Alexey-T** [comment]
![gu](https://user-images.githubusercontent.com/4154978/193418361-49e1084b-3b21-406c-b370-d437224b327c.png)

**Comment by yonist** [comment]
Cool. Thanks! 

Another question. Is there an easy way to scroll to the bottom automatically ? when I Strings.LineAdd the scroll bar position doesn't change

**Comment by Alexey-T** [comment]
Ed.DoCommand() with
cCommand_ScrollToEnd or
cCommand_GotoTextEnd

**Comment by yonist** [comment]
I got it work in a very ugly way, the following doesn't work:

```
FEditor.Strings.LineAddRaw(' ',cEndNone,false);
FEditor.Update(true);
FEditor.DoCommand(cCommand_ScrollToEnd ,cInvokeInternal);
```
What I did was to post a message to the form and then call to DoCommand which works fine. Do you think on a better way? (it also doesn't work in the OnChange event handler)

**Comment by Alexey-T** [comment]
This works on linux
```
procedure TForm1.Button1Click(Sender: TObject);
begin
  ed.strings.LineAdd('eeeee');
  ed.Update(true);

  ed.DoCaretSingle(0, ed.Strings.Count-1);
  ed.DoScrollToBeginOrEnd(false);
end;
     
```

**Comment by yonist** [comment]
Not on windows :-( 

I'll use my own solution for the time being. Thanks.

**Comment by yonist** [comment]
It could be the result of my own code. checking...

**Comment by Alexey-T** [comment]
This is good on win10
```
procedure TForm1.Button1Click(Sender: TObject);
begin
  ed.strings.LineAdd('eeeee');
  ed.Update(true);

  Application.ProcessMessages;
  ed.DoCaretSingle(0, ed.Strings.Count-1);
  ed.DoScrollToBeginOrEnd(false);
  ed.Update();
end;
```

don't send messages to your form. use APplication.ProcessMessages.

**Comment by yonist** [comment]
I wasn't very clear what the problem is, I do the processing (i.e. adding lines) inside of an event handler (OnKeyDown) in that case DoScrollToBeginOrEnd doesn't work. In the example you send me the Button1Click is the same as my solution on posting message to the form in the sense that the control completed the work (of the KeyDown) and it now accepts an external input 

p.s. I really like cudatext.

**Comment by Alexey-T** [comment]
So Application.ProcessMessages call, if added, solved your problem?

**Comment by yonist** [comment]
No. 
And there is not reason it will, because OnKeyDown is blocked. so the control doesn't paint and calculate the new offsets.

**Comment by Alexey-T** [comment]
>I really like cudatext.

Good... if feedback, welcome to Github 'issues'.

**Comment by yonist** [comment]
Hi, 

I pushed a new version.

It took awhile because of the scrolling problem. I had to make 2 small changes to TATSynEdit that helped me a lot and simplified my code. 
I also hope you are willing to expose FCaretShowEnabled variable (make it a property), it will make the console behave much better and also will simplify the code. 

I still need to figure out how to control the "cut" operation only let it cut when the marked text is on the last line. If you have any ideas that would be great. 

Thanks

**Comment by yonist** [comment]
> > I really like cudatext.
> 
> Good... if feedback, welcome to Github 'issues'.

Just one question, what you wish cudatext would be? a replacement to Notepad++ ? to compete with VSCode?

**Comment by Alexey-T** [comment]
>what you wish cudatext would be? a replacement to Notepad++ ? 

Yes! with cross-platform support.

> expose FCaretShowEnabled variable (make it a property)

done.
what more changes do you suggest, write here, so I don't need to dig into your code.

**Comment by Alexey-T** [comment]
```
  if Assigned(FOnCmdExecuteRequest) then
    FOnCmdExecuteRequest(self);
```
Why not to react to OnCommandAfter (or OnCommand)? instead of making new event.

**Comment by yonist** [comment]
It didn't work. Sometimes I need the text to change before DoCommand_TextInsertEol completes. Otherwise breaking an internal state and to fix it and the caret position on the screen proved to be to brittle

**Comment by yonist** [comment]
> done. what more changes do you suggest, write here, so I don't need to dig into your code.

I also added a new message and event:

const
  AFTER_MESSAGES_PROCCESSED = WM_USER + 739;

procedure MSAfterMessagesProcessed(var msg : TMessage); message AFTER_MESSAGES_PROCCESSED;

property OnAfterMessagesProcessed: TNotifyEvent read FOnAfterMessagesProcessed write FOnAfterMessagesProcessed; 

This enables to me to have a callback after TATSynEdit completed all the drawings, caret positioning and the scrolling with the entire internal state intact.

**Comment by Alexey-T** [comment]
Ok, I added your event as renamed OnCommandKeyEnter.

**Comment by Alexey-T** [comment]
```
const
AFTER_MESSAGES_PROCCESSED = WM_USER + 739;

procedure MSAfterMessagesProcessed(var msg : TMessage); message AFTER_MESSAGES_PROCCESSED;
```
can you send this message to your main form, not to ATsynedit? what code in ATsynedit uses this message?

**Comment by Alexey-T** [comment]
you have new message-code 739.
you send this message to ATsynedit fork?
then ATsynedit calls
```
procedure TATSynEdit.MSAfterMessagesProcessed(var msg: TMessage);
begin
  if Assigned(FOnAfterMessagesProcessed) then
    FOnAfterMessagesProcessed(self);

end;
```
so it fires the event.
so can you just fire the event from the main app without sending 739?

**Comment by yonist** [comment]
It just calls to an event assigned by the user, so if for example you are in a middle of processing one message (WM_KEYDOWN for example)  you can place a message that is *guaranteed* to run after everything is completed. 

procedure TATSynEdit.MSAfterMessagesProcessed(var msg: TMessage);
begin
  if Assigned(FOnAfterMessagesProcessed) then
    FOnAfterMessagesProcessed(self);
end; 

I don't think it is the right place to put it in the form. but it is your component so it is your call.

**Comment by yonist** [comment]
I think I'll change my component to inherit from TATSynEdit instead of wrapping it so I can move the message to it. 

I'll ping you after the weekend. 

Thanks.

**Comment by yonist** [comment]
I pushed new version TATConsole now it inherits from TATSynEdit. It works fine. 

I still need OnCmdExecuteRequest, but maybe it is better to change that to virtual procedure instead of an event

**Comment by Alexey-T** [comment]
>still need OnCmdExecuteRequest,

I added it as anotjher name - OnCommandKeyEnter, check the github.

**Comment by yonist** [comment]
Thanks! Implemented. 

One last thing: https://github.com/Alexey-T/ATSynEdit/commit/15327b2f8be4b9041adb1c6ba9586044a48639b4

Can you make it read/write property?

**Comment by Alexey-T** [comment]
>Can you make it read/write property?

ok, done.

**Comment by yonist** [comment]
Question:

In the case a command line, except for the last line the "hilite" of a give line cannot be changed over its life time. so calling OnCalcHilite will always result with the same output. 

Do you think it is a good idea to cache the TATLineParts for each line? is it worth it? Do you have such mechanism in place?

**Comment by Alexey-T** [comment]
such mechanism existed before. I measured how it helped - not much. with scrolling up/down. I removed it AFAIR.

**Comment by yonist** [comment]
It seems that Caret.Posx doesn't respect Unicode characters with **2 or more** bytes

For example place the following string in the editor: 123😸😸 
and set ATSynEdit1.Carets[0].PosX:=4  

It looks like the caret is being placed after the 4th **byte** instead of after the 4th **character** (😸 is a 2 bytes char) and the text becomes gibberish

**Comment by Alexey-T** [comment]
after the 4th WORDCHAR. where the string is encoded to UnicodeString.
you must adjust the PosX manually - 

```
function IsCharSurrogateAny(ch: widechar): boolean;
begin
  Result:= (ch>=#$D800) and (ch<=#$DFFF);
end;

function IsCharSurrogateHigh(ch: widechar): boolean;
begin
  Result:= (ch>=#$D800) and (ch<=#$DBFF);
end;

function IsCharSurrogateLow(ch: widechar): boolean;
begin
  Result:= (ch>=#$DC00) and (ch<=#$DFFF);
end;
```

from atstringproc.

**Comment by Alexey-T** [comment]
closing; let's create new topics.
