### ISSUE TITLE
BorderStyle vs OptBorderVisible

### ISSUE THREAD

**Issue by yonist** [Alexey-T/ATSynEdit#299]
Hi, 

I found that I've 2 methods to control the border (BorderStyle/OptBorderVisible). It is somewhat confusing. And if possible I think one of them should be removed. 

Otherwise it is good to add documentation regarding their respective behavior.

Thanks,

**Comment by Alexey-T** [comment]
1st is inherited. it is painted by LCL.
2nd is new one. painted inside the editor. both needed!
