### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by User4martin** [Alexey-T/ATSynEdit#3]
Heap dump by heaptrc unit
16101 memory blocks allocated : 4118435/4173704
16100 memory blocks freed     : 4118343/4173608
1 unfreed memory blocks : 92
True heap size : 393216 (128 used in System startup)
True free heap : 392912
Should be : 392928
Call trace for block $001ABC68 size 92
  $0043371F line 377 of ../../atsynedit/atcanvasproc.pas
  $0044244D line 2498 of ../../atsynedit/atsynedit.pas
  $00440813 line 1983 of ../../atsynedit/atsynedit.pas
  $00440A3F line 2006 of ../../atsynedit/atsynedit.pas
  $0056725B line 126 of include/customcontrol.inc

**Comment by Alexey-T** [comment]
fix made.
