### ISSUE TITLE
'End' key jumps to beginning of line

### ISSUE THREAD

**Issue by Andreas123456** [Alexey-T/ATSynEdit#30]
- Turn on "wrap at edge".
- Turn on "end of wrapped part: prefer next line pos".
- Enter some text so that wrapping occurs.
- Place the cursor in the middle of the first line.
- Press the 'End' key.

As a result, the cursor will jump to the beginning of the second (wrapped) line. It should jump to the end of the first line instead.

**Comment by Alexey-T** [comment]
End of 1st ln is caret pos which is after last char of 1st ln. so it blinks at next line. U wanted it

**Comment by Andreas123456** [comment]
My comment of yesterday was about the behavior of the 'Left' and 'Right' keys. My comment of today is about the behavior of the 'End' key. These are two different things.

What I want is that SynEdit behaves like SynWrite (and every other editor, except ST3).

**Comment by Alexey-T** [comment]
Sw does End-jmp to not LAST chr. but LAST-1 chr. u see it? make like Sw?

**Comment by Alexey-T** [comment]
SW does jump to last-1 chr of wrapline. Not to last. make like it?  other way (detect END press, not END) not good

**Comment by Andreas123456** [comment]
Okay, you are right, I forgot about the space character, which is the very last character in the first line.

Please make it like in SynWrite. In SynWrite, it's perfect.

![before](https://cloud.githubusercontent.com/assets/12023109/7291911/aaa98862-e996-11e4-9cd4-e83ea57cf707.png)

![after](https://cloud.githubusercontent.com/assets/12023109/7291918/b622e0ee-e996-11e4-833a-e3cd3658a86a.png)

**Comment by Alexey-T** [comment]
chk-"close" if ok

**Comment by Andreas123456** [comment]
It's fine now. Thank you.
