### ISSUE TITLE
Is there away to prevent the Caret following the mouse when selecting text?

### ISSUE THREAD

**Issue by yonist** [Alexey-T/ATSynEdit#301]
The text input caret position changes when the user select a text. I would like to prevent that and keep the caret in its original position while still enable the selecting of the text. Is there a simple way to achieve this?

This is how it works, for example, in windows terminal.  
![image](https://user-images.githubusercontent.com/499992/202004645-d6c9190a-3a3c-49ad-95cd-963a64192302.png)

**Comment by Alexey-T** [comment]
no way. selection is part of a caret. no selectioon w/o caret possible.

**Comment by yonist** [comment]
Is there away to disable selection?

**Comment by Alexey-T** [comment]
yes

![se](https://user-images.githubusercontent.com/4154978/202006909-d3988243-6ae7-4c93-a378-309ce5c04ddb.png)

**Comment by yonist** [comment]
Thanks
