### ISSUE TITLE
Compile Error - Version 2022.11.22

### ISSUE THREAD

**Issue by rayhester** [Alexey-T/ATSynEdit#304]
Hi Alexey

On Windows 11, I get this error:

Compile ATSynEdit error: atsynedit.pas(8262,9) Error: Wrong number of parameters specified for call to 					         "CanvasPaintPlusMinus"

Seems to be missing the APenWidth parameter

If I add a value for the pen width it compiles:

  CanvasPaintPlusMinus(C,
    ALineColor,
    Colors.GutterFoldBG,
    Point(AX, AY),
    EditorScale(FOptGutterPlusSize),
    1,     // Add a  PenWidth value
    APlus);

Thanks

Ray

**Comment by Alexey-T** [comment]
Update ATFlatControls
