### ISSUE TITLE
Selection breaks on highlighting

### ISSUE THREAD

**Issue by yonist** [Alexey-T/ATSynEdit#308]
I have a simple highlighter that I run in the OnCalcHilite event handler. This however breaks selected text indication, while the text is still being selected it is not painted as so.

The text and the cursor positioned at the beginning of the text
![image](https://user-images.githubusercontent.com/499992/222496248-c34f74c3-c6a7-48aa-9217-1864932c08cd.png)

The text after selecting (using shift + right arrow) 
![image](https://user-images.githubusercontent.com/499992/222496430-38619d0b-f345-41fc-8e54-bbc64ea6a139.png)

Only the first token is drawn as selected (although everything is selected as expected and ctrl+x cut the expected text). 

Any idea what is wrong?

**Comment by Alexey-T** [comment]
my code TATSynEdit.DoCalcLineHilite shows that 1) code gets coloring form adapter or OnCalcHilite, 2) it applies the selection.

**Comment by yonist** [comment]
No Len=0. 
But if it works on your side it is probably an issue with my code. I'll double check. and look what  DoCalcLineHilite does

**Comment by Alexey-T** [comment]
it is good to show 'dump of LineParts', ie result of what your handler calculates. in a text.

**Comment by yonist** [comment]
Thanks, that seems to be the problem. I miss calculated one of the offsets.
