### ISSUE TITLE
What data structure to use for storing words for autocomplete? 

### ISSUE THREAD

**Issue by yonist** [Alexey-T/ATSynEdit#309]
Currently I'm using SQLite with raw calls and in-memory mode, for 80k words dictionary finding 20 matches takes 0.1ms on my 15 years old pc and  0.02ms on my 4 years old machine. These are good numbers. but not optimal in regard for the memory it consumes... 

I was wondering what are you using? 

Thanks

**Comment by Alexey-T** [comment]
i cannot guess that is 'storing words for autocomplete'.

**Comment by Alexey-T** [comment]
cudatext passes raw string (which is LF-separated lines) of all autocomplete words.

**Comment by yonist** [comment]
Suppose the user in cudatext opens a project, I assume it parses the text
to get all the tokens: function names, class names etc...
All these tokens has to be stored somewhere. So when the user writes the
prefix it will show relevant suggestions.

What data structre you are using to store all the tokens?

**Comment by Alexey-T** [comment]
- each 'token' is a record (x-y coords, link to lexer rule)
- all tokens are in TList, list item is casted to token
