### ISSUE TITLE
Two problems with 'Cursor Up' key

### ISSUE THREAD

**Issue by Andreas123456** [Alexey-T/ATSynEdit#31]
Set up the following scenario:

![up](https://cloud.githubusercontent.com/assets/12023109/7303545/c9273310-e9f1-11e4-9461-73a4673dc41e.png)

Now press the 'Cursor Up' key two times.

Problem 1: After pressing 'Cursor Up' the first time, the cursor will move to the letter "h". It should move to the space after the letter "g" instead.

Problem 2: Pressing 'Cursor Up" the second time has no effect at all.

**Comment by Alexey-T** [comment]
Fix, beta in 2hrs

**Comment by Alexey-T** [comment]
i see @BBasile liked. Basile, feel free to test if you want, demo_editor program. or http://uvviewsoft.com/bb/demo.zip

**Comment by Andreas123456** [comment]
It's fine now. Thank you.
