### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by z4ziggy** [Alexey-T/ATSynEdit#310]
I was able to trace down the DC memory leaks down to the ` TATSynEdit.UpdateCharSize` procedure.

Commenting out the `TCanvas.Create` block results in a clean memory on exit. Since I am not familiar enough with the code, I have no idea of the implications of this, however if this behavior is needed it can be resolved by creating the DC prior (eg, on the OnCreate or similar) and releasing it properly.  For now, the following patch solves the memory leaks:

<pre>
diff --git a/atsynedit/atsynedit.pas b/atsynedit/atsynedit.pas
index 0ad6e3b..07535c9 100644
--- a/atsynedit/atsynedit.pas
+++ b/atsynedit/atsynedit.pas
@@ -3392,6 +3392,7 @@ begin
   begin
     Size:= C.TextExtent(SampleStr);
     UpdateFontProportional(C);
+  {
   end
   else
   begin
@@ -3407,6 +3408,7 @@ begin
     finally
       FreeAndNil(TempC);
     end;
+  }
   end;
 
   ACharSize.XScaled:= Max(1, Size.cx) * ATEditorCharXScale div SampleStrLen;
</pre>

**Comment by Alexey-T** [comment]
This is not OK fix, you commented the calculation of char-width for the case "not C.HandleAllocated". it occurs when app starts and loads editor history for the editor, before drawing the editor. it may lead to not OK loading of editor history. What is bad in that block -->

```
    TempC:= TCanvas.Create;
    try
      dc:= GetDC(0);
      TempC.Handle:= dc;
      TempC.Font.Name:= Self.Font.Name;
      TempC.Font.Size:= DoScaleFont(Self.Font.Size);
      Size:= TempC.TextExtent(SampleStr);
      UpdateFontProportional(TempC);
      ReleaseDC(dc, 0);
    finally
      FreeAndNil(TempC);
    end;
```

**Comment by z4ziggy** [comment]
I totally agree this is a **BAD** patch. However, it will take me a LONG time to learn all your code, so I chose the 'quick and dirty' patch to solve the memory leaks which kills my tiny pc.

Now in regards to fixing the code - my guess is the DC not being released properly (although I did play with code for a while, and I have to admit I have no idea why it's not released albeit the `ReleaseDC(dc,0)`) so my suggestion instead of creating a temp TCanvas each paint (when "not C.HandleAllocated") do it initially on the OnCreate and release it on your OnDestroy. Although this is just a guess. and maybe it's the `GetDC(0)` which causes the leak - obviously further debugging is needed. I'm just happy I was able to trace down the culprit.

As I've said, I simply don't know your code AT ALL, and it will take me ages to learn it all. So I'm going step by step, trying to fix my problems before actually contributing code.

**Comment by Alexey-T** [comment]
Also can you try to remove GetDC/ReleaseDC calls, like in this example?
```
    uses Types;
     
    function GetTextExtend(const AString: string; const AFont: TFont): TSize;
    var
      LCanvas: TCanvas;
    begin
      LCanvas := TCanvas.Create;
      try
        LCanvas.Font := AFont;
        Result := LCanvas.TextExtent(AString);
      finally
        LCanvas.Free;
      end;
    end;
```

**Comment by Alexey-T** [comment]
Before trying your changes,try this Git branch:

[fixing_mem_leak](https://github.com/Alexey-T/ATSynEdit/tree/fixing_mem_leak)

**Comment by z4ziggy** [comment]
> Before trying your changes,try this Git branch:
> 
> [fixing_mem_leak](https://github.com/Alexey-T/ATSynEdit/tree/fixing_mem_leak)

Works perfectly. No DC leaks 👍 And code is much better than my ugly patch 😂

Much thanks for your quick and perfect fix. I hope to be able to contribute better code in the future...

**Comment by Alexey-T** [comment]
Thank you too for report.
Did you try CudaText, maybe compare it with your current editor?

**Comment by z4ziggy** [comment]
I'm trying to switch to CudaText as my main GUI editor, which is why I'm trying to fix those bugs. Atm it looks promising, I like it's speed and the Lazarus code made me nostalgic (ye, Delphi 6...). Many thanks to all your hard code, as I saw CudaText and ATSynEdit aren't your 1st attempts in creating an editor - kudos for the persistence ❤️

**Comment by yonist** [comment]
@z4ziggy How did you find about the memory leak? What tool did you use?

@Alexey-T I noticed that UpdateCharSize is being called on every key press or mouse click... while the result doesn't change (i.e. it is the same font and the same size).
On my low spec machine I did basic caching and the editor feels much more snappy and responsive (this is an old machine, from 2010) on my desktop (from 2019) there wasn't any noticeable difference (the latency was no more then 0.2ms)

**Comment by Alexey-T** [comment]
Please share your changes, @yonist

**Comment by Alexey-T** [comment]
I made simple caching in UpdateCharSize, tell me is it better now? I made time-check and I saw that UpdateCharSize works about 4-5msec here (w/o cache)

**Comment by yonist** [comment]
I'll check your changes later today, I did something very naive and different.. 

I added to TATEditorCharSize record a new field
    `CalcDuringPaint: boolean;`

On the constructor I set it to false:
`FCharSize.CalcDuringPaint:= true;`

On the calling site I did:
```
if FCharSize.CalcDuringPaint then
    UpdateCharSize(FCharSize, C, FSpacingY);  
```

And in UpdateCharSize I set it to false:
`ACharSize.CalcDuringPaint:= false;`

I didn't invalidated the cache at all.... But if I had to it I would reset `CharSize.CalcDuringPaint` in the `self.font.OnChange` event as well as in the `SetOptScaleFont`. 

I did measure a lower latency, but just remember that on 120hz monitor you have about 8.3ms to paint a window before you start dropping frames. And spending 5ms on that code path will sure result in not so good experience 
  
Thanks

**Comment by Alexey-T** [comment]
For cache reset, I need to check not only TFont change , but all these (in github already):
```
  if (FPrevFontName=Self.Font.Name) and
    (FPrevFontSize=Self.Font.Size) and
    (FPrevFontSpacingY=ACharSpacingY) and
    (FPrevScale_OptScaleFont=FOptScaleFont) and
    (FPrevScale_GlobalScale=ATEditorScalePercents) and
    (FPrevScale_GlobalScaleFont=ATEditorScaleFontPercents) then exit;

  FPrevFontName:= Self.Font.Name;
  FPrevFontSize:= Self.Font.Size;
  FPrevFontSpacingY:= ACharSpacingY;
  FPrevScale_OptScaleFont:= FOptScaleFont;
  FPrevScale_GlobalScale:= ATEditorScalePercents;
  FPrevScale_GlobalScaleFont:= ATEditorScaleFontPercents;  
```

**Comment by z4ziggy** [comment]
> @z4ziggy How did you find about the memory leak? What tool did you use?

The memory leaks where reported on the console Exit with `TGtk2WidgetSet.Destroy` complaining about leftovers.

I removed as much code as I could from the CudaText binary to make my life easier while debugging, and used `gdb` to trace the executable and watch the memory regions which were reported.

**Comment by yonist** [comment]
@z4ziggy thanks, I'm on windows. That might explain why I didn't see the original bug you reported.

@Alexey-T I tried something that speed everything even more, again it doesn't invalidate correctly BUT it so much faster
```
if not firstTime then begin
    UpdateInitialVars(C);
    firstTime:= true;
  end;
```

**Comment by Alexey-T** [comment]
I added time-check in `   UpdateInitialVars`:
```
procedure TATSynEdit.UpdateInitialVars(C: TCanvas);
var
  t: qword;
begin
  t:= GetTickCount64;
...
  t:= GetTickCount64-t;
  writeln('ini '+inttostr(t));
end;
```

test it with latest atsynedit. it prints to STDOUT in Linux:

21
0
0
0
0
0
0

so only first run takes 20msec, next are 0msec. it's OK, no need more speedup.

**Comment by yonist** [comment]
I get different numbers. And on my old PC it feels much more responsive. 

Anyway thank for the new fix. It is already better.

**Comment by Alexey-T** [comment]
Your last change was not ok, of course, so what do you suggest to change ? Without break!

**Comment by yonist** [comment]
I mean the last change you did, the one with the FPrevFont record. It really made things better.

**Comment by Alexey-T** [comment]
Good, tkx
