### ISSUE TITLE
Changing pasted text before inserting

### ISSUE THREAD

**Issue by yonist** [Alexey-T/ATSynEdit#312]
I need to change the text users are adding via pasting (ctrl+v) but I couldn't find a place were it can done easily. Any idea?

**Comment by Alexey-T** [comment]
OnPaste event exists.

more general way: handle OnCommand to change work of __any__ command

**Comment by yonist** [comment]
I saw the OnPasete event but the actual text from the clipboard is not being passed:

`
function TATSynEdit.DoCommand_ClipboardPaste(AKeepCaret, ASelectThen: boolean;
  AClipboardHasColumnBlock: boolean; const AClipboardText: string
  ): TATCommandResults; 
begin
...
if Assigned(FOnPaste) then
  begin
    bHandled:= false;
    FOnPaste(Self, bHandled, AKeepCaret, ASelectThen);
    if bHandled then exit;
  end;
...
end;

`

I'll have a closer look on the OnCommand, thanks.
