### ISSUE TITLE
atsynedit_unicodedata

### ISSUE THREAD

**Issue by yonist** [Alexey-T/ATSynEdit#317]
I'm looking for ways to reduce my EXE size. Is there a reason why you didn't use Win32 native functions?

Like:
[GetStringTypeW](https://devblogs.microsoft.com/oldnewthing/20190218-00/?p=101056), IsCharAlphaNumericW , [IsCharUpperW](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-ischarupperw)  etc..

**Comment by Alexey-T** [comment]
For cross platform support.

**Comment by yonist** [comment]
On Linux/Mac you have ICU (it also has a version for windows, but I don't think it present in the basic installation)

**Comment by Alexey-T** [comment]
CudaText supports much more OSes… and it’s bad to ask user to install ICU..
