### ISSUE TITLE
Strange behavior of 'Cursor Down' key

### ISSUE THREAD

**Issue by Andreas123456** [Alexey-T/ATSynEdit#32]
Set up the following scenario:

![down](https://cloud.githubusercontent.com/assets/12023109/7314011/3a82351e-ea60-11e4-9255-975b8fef1d75.png)

Then press the 'Cursor Down' key.

Expected result: The cursor will be after the letter "u".
Actual result: The cursor will be after the letter "t".

**Comment by Alexey-T** [comment]
it's same as for Up key: code sees it goes to "end of part" and goes to end-1... i ll try to fix
