### ISSUE TITLE
autocompletion listbox is no good with big fonts.

### ISSUE THREAD

**Issue by veksha** [Alexey-T/ATSynEdit#321]
https://github.com/Alexey-T/ATSynEdit/assets/275333/bb19019f-64c4-4ca4-9909-5794933b29e1

scale settings:

![image](https://github.com/Alexey-T/ATSynEdit/assets/275333/738461d2-177f-435b-8753-04a83154b1df)

**Comment by Alexey-T** [comment]
Made a fix. better?

**Comment by Alexey-T** [comment]
Try to change video encoder . I cannot see the video on Linux .

**Comment by veksha** [comment]
> Try to change video encoder . I cannot see the video on Linux . I must save it to file. To see it.

seems that yuv444 is supported only by chromium-based browsers? in firefox i can't see my videos.
ok. i will change to yuv420.

> Made a fix. better?

yes! thanks.
