### ISSUE TITLE
 Can't compile package atsynedit_package.lpk

### ISSUE THREAD

**Issue by Gzushgshsh** [Alexey-T/ATSynEdit#325]
I try to install from OPM and get this error

> atsynedit.pas(8956,9) Error: Identifier not found "IM_Context_Set_Cursor_Pos"

System: MX-Linux 23 (Debian 12), Lazarus from debian repository

**Comment by Alexey-T** [comment]
GTK2 error on ATSynEdit compiling regarding IME
https://wiki.freepascal.org/CudaText

**Comment by Gzushgshsh** [comment]
Thanks for help me, it worked!

Detail: I got so lost looking that I ended up here
https://wiki.freepascal.org/ATSynEdit#Compilation_errors
