### ISSUE TITLE
"unprintable"+"show" influences to "show wrapped-indent vert line"

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/ATSynEdit#33]
В Сине это две независимые настройки.
В Демо верт.линии общих сдвигов (staple?) исчезают при выключении *скрытых символов*. Надеюсь это временно.

UPD Уже понял, что эти верт.линии не staple из Син. Они играют похожую роль. Считаю, что их отображение не нужно отображением скрытых символов.

**Comment by Alexey-T** [comment]
да недочет... Сори. вечером обновлю
