### ISSUE TITLE
IME form: code

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATSynEdit#333]
@rasberryrabbit 

```
  // draw text
  tm:=CompForm.Canvas.TextExtent(buffer);
```
here you cast 'array of widechar' to 'string'. it works but let's make better.
add `var bufferStr: string` and do

`bufferStr:= string(WideString(buffer))`.

then you can re-use bufferStr here:
`  CompForm.Canvas.TextOut(1,0,buffer);`

**Comment by rasberryrabbit** [comment]
Ok. I makes new pull request. 

[334](https://github.com/Alexey-T/ATSynEdit/pull/334)

**Comment by Alexey-T** [comment]
```
    FIMSelText: UnicodeString;
...
  if position>0 then
    for i:=0 to position-1 do
      s:=s+FIMSelText[i]; 
```

here you write 0-th char! bad. it must crash.

**Comment by rasberryrabbit** [comment]
Fixed.  
  
[335](https://github.com/Alexey-T/ATSynEdit/pull/335)
