### ISSUE TITLE
commands: "sel: ext sel by line" and "sel: sel lines at carets" 

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/ATSynEdit#34]
У команды **sel: ext sel by line** странное поведение, не совпадающее с ее именем. Она продолжает тек.выделение (в т.ч. просто каретку) до конца строки, вместо того, чтобы включить в выделение **всю** строку с кареткой.

Команда **sel: sel lines at carets** забывает включить в выделение eol.

**Comment by Alexey-T** [comment]
про 1. Это для сублимистов. Видите в selection menu? отличается разве. Про 2-а нужен он eol?

**Comment by Alexey-T** [comment]
Суб-выделяет до начала ctrl-l, надо поправить чтобы так же. как он.

**Comment by Alexey-T** [comment]
про 2. если выделять eol, соседние СЛОЖАтся, т е сольются в один селект. Так незя

**Comment by kvichans** [comment]
2. Может быть ваше возражение верно для нескольких кареток (нужно разбираться), но для одной каретки текущее поведение не удобно. Син включает eol в выделение.

**Comment by Alexey-T** [comment]
-- для нескольких кареток 
да, так, а для одной каретки команда не нужна, можно ctrl+L -она выделит строку с eol
