### ISSUE TITLE
TATEdit draws a small square dot

### ISSUE THREAD

**Issue by rcla** [Alexey-T/ATSynEdit#341]
I am using Windows 11 64 bit.

I have a Form with a ATEdit1(TATEdit) and DateEdit1(TDateEdit).
```pascal
  TForm1 = class(TForm)
    ATEdit1: TATEdit;
    DateEdit1: TDateEdit; 
```

When I go inside DateEdit1 and later in ATEdit1, a draws a small square dot is drawn in the position where I write.

I am attaching a gif where I captured the bug that appears:
![test](https://github.com/user-attachments/assets/e52d401f-130f-4e69-9884-a3161416a46d)

I appreciate the help.

**Comment by Alexey-T** [comment]
here I don't have Windows PC, in the nearest month-two. so I can test on Linux, or on the Wine.
can you repro on Linux or Wine?

**Comment by rcla** [comment]
At the moment I only have a Windows computer.

I am attaching a test program.
[test_atedit.zip](https://github.com/user-attachments/files/16609294/test_atedit.zip)

**Comment by Alexey-T** [comment]
no repro on Wine on Xubuntu 22.
so I cannot help in the nearest month.

try this: in Object Inspector, find 'Caret' props and 'Blink' props. try to change them. try to toggle for example this prop: OptCaretStopUnfocused.

**Comment by rcla** [comment]
I tried different properties of 'Caret', 'Blink' and 'DoubleBuffered', but still having the same issue.

**Comment by Alexey-T** [comment]
project1.exe compiled. 
[project1exe.zip](https://github.com/user-attachments/files/16613454/project1exe.zip)

@miroslavmatas, Hi, do you confirm the bug on this compiled exe?

**Comment by MiroslavMatas** [comment]
> project1.exe compiled. [project1exe.zip](https://github.com/user-attachments/files/16613454/project1exe.zip)
> 
> @MiroslavMatas, Hi, do you confirm the bug on this compiled exe? if yes, do you see it on CudaText on single-line inputs?

but do not see it on CudaText side…
any suggestion for good GUI/Dialog for checking it?

**Comment by MiroslavMatas** [comment]
![image](https://github.com/user-attachments/assets/816bd61f-4a68-42e8-9542-4790912156e2)

all is ok here

**Comment by Alexey-T** [comment]
thanks.
pls try these things:

1. add OnEnter event for ATEdit1 and code for it: `ATEdit1.Update`. as workaround.
2. set ATEdit1.CaretShapeNormal to different height, e.g. 80%.

**Comment by Alexey-T** [comment]
1b. add OnEnter which runs a Timer. Timer1.OnTimer must run `ATEdit1.Update; ATSynEdit1.Update; .....`

**Comment by Alexey-T** [comment]
ok, what if you set param AForceRepaint of Update() ?

`  ATEdit1.Update(false, true);`

do it with Timer. in OnTimer:
```
Timer1.Enabled:= false;
Timer1.Enabled:= true;
```

**Comment by rcla** [comment]
I tried with
```pascal
procedure TForm1.ATEdit1Enter(Sender: TObject);
begin
  Timer1.Enabled:= false;
  Timer1.Enabled:= true;
end;

procedure TForm1.FormCreate(Sender: TObject);
begin
  ATEdit1.CaretShapeNormal.Height := 10;
  Timer1.Enabled := False;
end;

procedure TForm1.Timer1Timer(Sender: TObject);
begin
  Timer1.Enabled:= false;
  ATEdit1.Update(false, true);
end;
```

But it remains the same.

**Comment by Alexey-T** [comment]
if you set caret-color to green
```
procedure TForm1.FormCreate(Sender: TObject);
begin
  ATEdit1.Colors.Caret:= clGreen;
end; 
```

then parasite dot is also green?

**Comment by rcla** [comment]
> if you set caret-color to green
> 
> ```
> procedure TForm1.FormCreate(Sender: TObject);
> begin
>   ATEdit1.Colors.Caret:= clGreen;
> end; 
> ```
> 
> then parasite dot is also green?

The parasite dot does not change color.

**Comment by Alexey-T** [comment]
It is black, so change all Colors items which are black, to Red, until you get Red  bad dot. This may help us to find guilty ui code

**Comment by Alexey-T** [comment]
[black or dark grey]

**Comment by Alexey-T** [comment]
try this, pls:

3. in atsynedit.pas, comment this
```
  //force selection-frame during column selection
  if FOptShowMouseSelFrame or FMouseDownAndColumnSelection then
    if FMouseDragCoord.X>=0 then
      DoPaintMouseSelFrame(C);
```

**Comment by rcla** [comment]
I changed the color: 
```pascal
  ATEdit1.Colors.BlockSepLine := clRed;
  ATEdit1.Colors.BlockStaple := clRed;
  ATEdit1.Colors.BlockStapleForCaret :=clRed;
  ATEdit1.Colors.Caret:= clRed;
  ATEdit1.Colors.GutterCaretFont := clRed;
  ATEdit1.Colors.GutterFoldLine := clRed;
  ATEdit1.Colors.GutterFont := clRed;
  ATEdit1.Colors.GutterSeparatorBG := clRed;
  ATEdit1.Colors.IndentVertLines := clRed;
  ATEdit1.Colors.MinimapTooltipBorder := clRed;
  ATEdit1.Colors.RulerFont := clRed;
  ATEdit1.Colors.StateSaved := clRed;
  ATEdit1.Colors.TextDisabledFont := clRed;
  ATEdit1.Colors.TextFont :=clRed;
  ATEdit1.Colors.TextHintFont := clRed;
  ATEdit1.Colors.UnprintedHexFont :=clRed;  
```

> try this, pls:
> 
> 3. in atsynedit.pas, comment this block
> 
> ```
>   //force selection-frame during column selection
>   if FOptShowMouseSelFrame or FMouseDownAndColumnSelection then
>     if FMouseDragCoord.X>=0 then
>       DoPaintMouseSelFrame(C);
> ```


I commented out that block, and then "Clean up and Build"

But still the same issue.

**Comment by Alexey-T** [comment]
So dot is still black, not red?

**Comment by Alexey-T** [comment]
4. If you change caret shape, the width, to value>2, dot width changed too?

**Comment by rcla** [comment]
> So dot is still black, not red?
>
Still in black

> 4. If you change caret shape, the width, to value>2, dot width changes too?
>
```pascal
  ATEdit1.CaretShapeOverwrite.Width := 6;
  ATEdit1.CaretShapeNormal.Width := 6; 
```
The parasite dot does not change;

**Comment by Alexey-T** [comment]
5. try to disable this in atsynedit.pas
```
  FAdapterIME:= TATAdapterWindowsIME.Create;
```

**Comment by rcla** [comment]
> 5. try to disable this in atsynedit.pas
> 
> ```
>   FAdapterIME:= TATAdapterWindowsIME.Create;
> ```
YES, that works!

**Comment by Alexey-T** [comment]
pls, test this patch before I apply it:
https://github.com/Alexey-T/ATSynEdit/pull/342

**Comment by rasberryrabbit** [comment]
This is compiled example.  
[fix_caret_misdrawing.zip](https://github.com/user-attachments/files/16622067/fix_caret_misdrawing.zip)

**Comment by rcla** [comment]
> This is compiled example. [fix_caret_misdrawing.zip](https://github.com/user-attachments/files/16622067/fix_caret_misdrawing.zip)

I ran that example on my computer and it works fine, the parasitic dot is no longer showing.

Thank you all very much for your help.

**Comment by Alexey-T** [comment]
patch applied, closing.
