### ISSUE TITLE
How to use this in Lazarus IDE instead of SynEdit?

### ISSUE THREAD

**Issue by theonlyasdk** [Alexey-T/ATSynEdit#343]
I want to use ATSynEdit instead of the usual SynEdit that Lazarus IDE uses. I want to have the word-wrapping feature. Is there a way to use this editor instead of SynEdit in the Lazarus IDE?

**Comment by Alexey-T** [comment]
No, there is no way...

**Comment by theonlyasdk** [comment]
:(
