### ISSUE TITLE
key-combo...

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATSynEdit#35]
@User4martin I dont know how to make "ctl-K, ctrl-L" or "ctl-K, K, B" keys. If u have idea, how to make it... what handler need. for combo.

**Comment by User4martin** [comment]
Well at first you need code that makes sure that a lead-stroke of combo can never be a stand alone too.
e.g if ctr-k ctrl-b is a combo, then you can not have ctrl-k on its own. You wouldn't know if the user wants the combo or the single stroke
You can have it at the end of a combo ctrl-j ctrl-k.

As long as you hardcode the mapping there is no issue.

Then if you have a list, you need 3 searches

  FindSingleStrokeKey(k; TShortcut); // to find any standalone.
  FindComboLeadStrokeKey(k; TShortcut); // to find if k is at the start of a shortcut

If FindSingleStrokeKey returns, then just execute.

if FindComboLeadStrokeKey returns then you need to store the key, so you can use it on the next keyPress or KeyDown event.

If you have a stored Combo-LeadKey then you call
  FindComboStrokeKey(Lead, Second; TShortcut); 
where you pass the stored as Lead, and the actual as Second.

If no combo is found you can decide to either ignore the 2nd, or search it standalone.

**Comment by Alexey-T** [comment]
@User4martin maybe u don't want it: anyway i made it, whole day work. Combo is activated if u enable {$define test_combo}   this enables 

  {$ifdef test_combo}
  M.Add(cCommand_ZoomIn, 'zoom in', ['Ctrl+B', 'Ctrl+P'], []);
  M.Add(cCommand_ZoomOut, 'zoom out', ['Ctrl+B', 'Ctrl+B', 'Ctrl+M'], []);
  {$else}
  
these 2 combos work ok here, 2 and 3 key combo
