### ISSUE TITLE
fold and column select

### ISSUE THREAD

**Issue by User4martin** [Alexey-T/ATSynEdit#38]
if you fold some text, all cursor movement will tread the folded block as one line.
That is if you do any action moving the cursor a line down, and you were right before the fold, then you will be right after the fold.
That is correct (as in expected).

The exception is column selection

-  run demo
-  fold 11-20
-  caret at x=1 , y= 10

ctrl-shift-right
ctrl-shift-down
ctrl-shift-down
ctrl-shift-down

the caret will visit each hidden line. IMHO it should not.

It should go through the fold in one move and extend the selectio (selected column)n to all lines in the fold.

**Comment by Alexey-T** [comment]
Yep.. agree,todo
