### ISSUE TITLE
fold and goto line

### ISSUE THREAD

**Issue by User4martin** [Alexey-T/ATSynEdit#39]
- run demo
- fold 11-20
- goto line from menu, enter 15

Now lines 12-14 and 16-20 are hidden.
Line 15 is visible

But there is no fold marker or anything for the folded block 16 to 20.

Imho in such a case the entire block (11 to 20) should be unfolded. 
But splitting the block into 2 new folds, revealing just one line is fine too, as song as fold indicators are correctly shown.

---
A similar issue happens if
- run demo
- fold 11-20
- place caret in line 11
- press return

line 12 will be visible, but the fold marker is still at line 11 (though the first hidden line is line 13)

**Comment by Alexey-T** [comment]
curr logic is this: if line.ItemHidden =-1, line hidden total, and blue line shown above 1st full hidden ln.
if ItemHidden=1,2,3.... then ln hidden partially and [...] marker shown for this ln.
for this - works ok... no bug. ... Todo--- I unfold total range if GOTO inside range
