### ISSUE TITLE
Return adds 2 new lines

### ISSUE THREAD

**Issue by User4martin** [Alexey-T/ATSynEdit#4]
If on the very last line of the text, (where there is no new line at the end), press return. Watch the gutter, there are 2 new lines.

This can happen, if:
- the current last line has text, but no newline
- or if you go to the automatically created, empty last line.

**Comment by Alexey-T** [comment]
maybe it good. I cannot get non-eol line at end-this way...

**Comment by User4martin** [comment]
go last line
 press return, caret down, caret down
 press return, caret down, caret down
 press return, caret down, caret down

each return = 2 lines.

IMHO, if last line has no return, then new last line should not have either.

**Comment by Alexey-T** [comment]
Maybe good for user? user can't get non-eoled line

**Comment by User4martin** [comment]
But he always gets one without anyway

Take an empty editor (just line 1 (no eol yet)) 
1: |
and ender a + return.

1: a <eol>
2: |<eol>
3:

line 3 has no eol (there are 3 lines,, even though only one return was entered.
press cursor down
1: a <eol>
2: <eol>
3:|

press return
1: a <eol>
2: <eol>
3: <eol>
4: |<eol>
5:

line 5 has no eol. (but again 2 extra lines)

**Comment by Alexey-T** [comment]
i see -Good to fix, todo.

**Comment by Alexey-T** [comment]
fix done/ Close if ok
