### ISSUE TITLE
Need save 1st/cur viewed line when wrap on/off

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/ATSynEdit#41]
Версия Демо от 7 мая.
Из состояния wrap off
![wrap-07may-off](https://cloud.githubusercontent.com/assets/7419630/7513926/356beb0e-f4c1-11e4-9395-bd456211cf9d.JPG)
переход в состояние wrap edge 
![wrap-07may-edge](https://cloud.githubusercontent.com/assets/7419630/7513929/3b9200c2-f4c1-11e4-97e1-ba8f8d12d896.JPG)
происходит с потерей ориентации в тексте. 
Возможные улучшения
1. Cохранять на месте первую видимую строку (желательно).
2. Cохранять на месте текущую строку (для нескольких кареток не однозначно)

**Comment by Alexey-T** [comment]
хм,подумаю, наверное 1.

**Comment by Alexey-T** [comment]
Проблема не ядра а демы, сделал 1, updat. еще вагон опций :) если хотите

**Comment by kvichans** [comment]
Нужны пояснения про смысл опций
1. gen -- show cur line -- minimal part
2. gen -- last line on top
3. gutter -- cols -- nums ???  ???

**Comment by Alexey-T** [comment]
конечно-
1-показ только части строки, не всей длинной перенесенной строки. 2- как Син. можно крутить последнюю строку вверх.. верх контрола. 3- там 2 индеента. один лево от номера. другой право.

**Comment by kvichans** [comment]
1. 2. 3. - все не понятно

**Comment by Alexey-T** [comment]
2-делаем файл 200строк. Строка 200 не может бы ть у верха окна. Если опция, то может. ок?

**Comment by Alexey-T** [comment]
3-номер строки рисуется как индент1+число+индент2. размер индента 1 и 2.

**Comment by kvichans** [comment]
2. "может быть у верха"? Случайно обнаружил что это для работы мышкой. Я по привычке все клавиатурой - и не вижу разницы. Подозреваю, это только в Демо - потом и клавишами можно будет загнать посл.строку вверх. ок
3. ок

**Comment by Alexey-T** [comment]
"может быть у верха"- да. При скроле скроллбара мышой
