### ISSUE TITLE
Save options

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/ATSynEdit#42]
Все равно же потом опции будут как-то сохраняться. Почему бы уже в Демо не заложить этот механизм? Тяжко при каждом запуске одно и то же настраивать. Конечно, опции еще не устоялись, так пусть сохраняются "как есть" - новые и переименованные можно будет "донастраивать".

**Comment by Alexey-T** [comment]
хмм потому что потом- будет Пи, он будет сейвить в json, а сщас его нет, есть какая-то штука в Лазе но не знаю

**Comment by Alexey-T** [comment]
@user4martin Do u know way to easy save all my editor into Lfm on press OK in opt form? and restore on calling Opt form. Easy with N calls..

**Comment by kvichans** [comment]
> потом- будет Пи, он будет сейвить в json

Плохая идея. Переносить во внешний сервис важдный для ядра функционал значит сразу закладывать мину в приложение. Вы не сможете гарантировать бесперебойную работу Пи

**Comment by Alexey-T** [comment]
Суб тоже работает при без питона, надо так сделать

**Comment by kvichans** [comment]
Про сохранение настроек в Демо. Появится?

**Comment by Alexey-T** [comment]
если узнаю как *легко* это делать

**Comment by User4martin** [comment]
I assume: Outside the IDE?

I haven't really looked at streaming. So I don't know. 

A few hints: Streaming is done based on TWriter and TReader 
fpc_2.6.4\rtl\objpas\classes\classesh.inc  line 1407
You can search the IDE code for that.

Alternatively, there are classes to stream to xml. TRttiXMLConfig
lazarus\components\lazutils\laz2_xmlcfg.pas
It does not support nested objects, It only streams certain types.

**Comment by Alexey-T** [comment]
нашел...Ура. забыл про код. меню- save/load

**Comment by Alexey-T** [comment]
Лучше так а не по ОК чтобы сейвить размер фонта, врап. Guter не сейвится
