### ISSUE TITLE
Not all options are saved

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/ATSynEdit#44]
Спасибо за команды сохранения настроек
Может быть работа над этим еще не закончена?
Вот настройки, которые не сохраняются
- unprinted -- tab-arrow len
- unprinted -- tab-arrow pointer size

**Comment by Alexey-T** [comment]
-над этим еще не закончена?
там типы настроек, published, public, var. Только первые сейвятся пока( tab len это третее)

**Comment by Alexey-T** [comment]
может потом.
