### ISSUE TITLE
Drag into minimap dont saves horiz scroll for main text

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/ATSynEdit#45]
Если (1) текст из длинных строк (несколько ширин окна), (2) wrap off, то drag подцвеченного куска в minimap вверх-вниз приводит к перемещению горизонтального скрола в осн. тексте в крайнее правое положение

**Comment by Alexey-T** [comment]
fix. Вроде лучше?

**Comment by Alexey-T** [comment]
если что, откройте тему.
