### ISSUE TITLE
Wrong word-wrapping

### ISSUE THREAD

**Issue by Andreas123456** [Alexey-T/ATSynEdit#51]
The letter "e" should be directly under the letter "a"..

![wrong_word-wrapping](https://cloud.githubusercontent.com/assets/12023109/8277122/8a858290-18bf-11e5-88a2-5d9e2485023e.png)

**Comment by Alexey-T** [comment]
limitation: of small wind widht. I keep 20 chars at right. At big size: Ok

**Comment by Andreas123456** [comment]
Okay, so then it's a feature, not a bug :-)
