### ISSUE TITLE
Word-wrap shouldn't be done at "." character

### ISSUE THREAD

**Issue by Andreas123456** [Alexey-T/ATSynEdit#52]
It's not good to have a single "." character at the beginning of a line due to word-wrapping.

![dot](https://cloud.githubusercontent.com/assets/12023109/8277133/c1729112-18bf-11e5-850f-6d73c88abe1f.png)

**Comment by Alexey-T** [comment]
Situation. App ll have option "wordchars"- if u set to it "." then u have ok result. Option exists at http://uvviewsoft.com/bb/demo.zip (dialog)

**Comment by Andreas123456** [comment]
Okay, good.
