### ISSUE TITLE
Double allocation of Ctrl+U

### ISSUE THREAD

**Issue by Andreas123456** [Alexey-T/ATSynEdit#53]
Double allocation of Ctrl+U:
- toggle word-wrap mode
- unindent selection

**Comment by Alexey-T** [comment]
WIll fix; yet it's Ctrl-u for wrap; what key you suggest? ctrl-w: no, cannot. no key?

**Comment by Andreas123456** [comment]
The usual keys for indent/unindent selection are tab/shift-tab. So I would suggest:

Ctrl+U: Toggle word-wrap mode
Tab: Indent selection
Shift-Tab: Unindent selection

**Comment by Alexey-T** [comment]
maybe Okey..
