### ISSUE TITLE
Delphi support

### ISSUE THREAD

**Issue by noname00-pas** [Alexey-T/ATSynEdit#54]
Dear Alexey-T,

Does ATSynedit support Delphi or is there any plan for Delphi support?

Thanks

**Comment by Alexey-T** [comment]
Hi.No at a moment; I don't have Rad st. And no motivation

**Comment by Alexey-T** [comment]
I need at last RAD St license.

**Comment by Alexey-T** [comment]
Have idea how can i get free license to Delphi XE8 Pro?

**Comment by noname00-pas** [comment]
Oh, sorry. I can help you this thing.
