### ISSUE TITLE
Shift cursor right, past EOL creates an invisible selection

### ISSUE THREAD

**Issue by User4martin** [Alexey-T/ATSynEdit#6]
Place the caret past the end of a line.
Normally if a char is inserted, spaces are filled to the visible pos of the caret, and the char appears at the correct pos.

Place the caret past the end of a line.
Press Shift-right several times.
The caret will move. There is no visible selection

But if you press any char, the caret jumps back to where you started Shift-right and the char is inserted there (as if there had been a selection)

**Comment by User4martin** [comment]
Also the right/left key jump between the start/end of that invisible selction

**Comment by Alexey-T** [comment]
to solve: i must render long line with spaces(line "aa"-- render "aa________________________________________"); it slows down so Maybe later

**Comment by Alexey-T** [comment]
Dont know what to do with it. i paint full sel area for col sel. not for stream sel. if paint full area for stream sel, i need more work: calc coords for this sel, more work needed. (for col sel it's simple)

**Comment by User4martin** [comment]
I havens looked deep enough at your code. So I cant comment on where to fix it. 

I see a IsPosSelected in DoCalcLineHilite, so I guess you need to check if a caret with selrection is past the end of line?

**Comment by Alexey-T** [comment]
before DoCalcLineHilite i do  DoPaintSelectedLineBg- here i paint ghost sel (column sel or norm)

**Comment by Alexey-T** [comment]
no plan to do it.

**Comment by Alexey-T** [comment]
Now i think how to make/fix it, sorry for delay, now i think it's valid wish.

**Comment by Alexey-T** [comment]
Some fix made (not 100% ok, full with JP chars give selection offset..)
