### ISSUE TITLE
block selection (alt-shift) and tabs. 

### ISSUE THREAD

**Issue by User4martin** [Alexey-T/ATSynEdit#8]
If a line contains tab, or Japanese chars (full width)

abcdef // no tabs
--->----->123456 // tabs 

place caret between  b and c
press
  shift-alt-right
  shift-alt-down

The selected part in the 2nd line is way too the right of that in the first line. Imho, it should be nearest to the desired position, so either start before, or start after the first tab.

**Comment by Alexey-T** [comment]
as made, it's RAW positions [x1,x2], not tabs counted(maybe I count tabs ltr? yet it's as designed)
