### ISSUE TITLE
Finder exists

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATSynEdit#80]
@kvichans
Hello; сделал такой об-ект, и тестировать его можно если хочется- он есть в демо app/demo_editor как диалог поиска. там несколько опций. Даже есть regex. 

есть одно "но"- я не выкладываю демо в Ехе, хорошо если поставите Лазарус и соберете демо. я помогу с этим. У меня Вин накрылась

**Comment by Alexey-T** [comment]
@Andreas123456 Hello; I have Find-rep dialog to test but with one "but": I cannot make Exe for Win32 so u need to install Lazarus and complile app/demo_editor. It's no good?

**Comment by Andreas123456** [comment]
I would like to test it. Installing Lazarus and compiling the app should be no problem. Please give me detailled instructions (Link to the Lazarus installer, link to the source files, and instructions how to compile them.)

**Comment by Alexey-T** [comment]
ok-good... http://www.lazarus-ide.org/ -intsaller for Win32 (don't get Win64). Install. "Donwload as zip" this atsynedit repo. In ide try "Project- Open" and select "app/demo_editor/nnnnnnnnn.lpi"

is LPI opened? then press green > at toolbar

**Comment by Alexey-T** [comment]
"download zip" button at root https://github.com/Alexey-T/ATSynEdit At right

**Comment by Andreas123456** [comment]
Okay, here are a few findings:

1. Non-ASCII characters are not found. For example, the Japanese characters in the test text are not found.

2. Search for "ddd" and then press F3 a few times. The behavior will depend on whether the "regex" option is activated. When it's activated, the caret will be moved by three characters eacht time F3 is pressed. When it's not activated, the cared will be moved by only one character. Why is the behavior different?

3. Search for "ddd" and then press F3 a few times. As a result, the "ddd"s in line 11 will be found. Then press "Cursor down" three times. As a result, the cursor will be in line 14. Then press F3 again. As a result, the cursor will jump back to line 11. That's not okay. The cursor should jump to the "ddd"s in line 20 instead.

4. Searching for "++" will cause a fatal error when the "regex" option is activated.

**Comment by Andreas123456** [comment]
Here is another one:
5. When you have a very long document (100000 lines or so), the performance is very, very bad. Other text editors are much faster, even with such long documents.

**Comment by Andreas123456** [comment]
Final one (for today):
6. Find what: "d". [x] From caret. "count all" ==> fatal error

**Comment by Alexey-T** [comment]
6) fixed. Tks..

**Comment by Alexey-T** [comment]
5)todo, just did it, now 100K lines file gives count of "a+" regex about 10-15 sec. 
count w-o regex is 1sec

**Comment by Alexey-T** [comment]
2, 4) fixed.

**Comment by Alexey-T** [comment]
Seems most done- check pls laster today? 

....new issues--new msg at Issues. You may see many flags in OPTs dialog

**Comment by Andreas123456** [comment]
I can confirm the following:

1. Not fixed.
2. Fixed.
3. Fixed.
4. Fixed.
5. Fixed.

**Comment by Alexey-T** [comment]
>Non-ASCII characters are not found

i don';t get idea. If i copy-paste cjk char to Find dlg - it found. If i enter regex "." if found. How not?

**Comment by Andreas123456** [comment]
Yes, regex "." is found. But cjk characters are not found (at least not for me -- I have no idea why we have different results here.) Also finding the character ä in a document which contains ä does not work for me.

**Comment by Alexey-T** [comment]
reason: Win where utf8 is not default. I test on Lin(will see win)

**Comment by Alexey-T** [comment]
#91 fixed 1)?

**Comment by Andreas123456** [comment]
Yes, 1.) is fixed.

**Comment by Alexey-T** [comment]
@User4martin maybe interested too...

**Comment by Alexey-T** [comment]
I cannot compare speed. i open file "test_files/lines 100k.txt" and do replaces: "a+" regex to "-". it takes long. is it long in other apps? I do replace "\w+" to "-" , it takes long too, much slower. is it ok.

**Comment by Andreas123456** [comment]
Okay, here are some benchmark figures:

EditPad Pro 7.8.3 x64:
    replace all "a+" regex with "-" in lines 100K.txt: < 1 second
    replace all "\w+" regex with "-" in lines 100K.txt: < 1 second

EmEditor v15.2.0 beta 2 x64:
    replace all "a+" regex with "-" in lines 100K.txt: < 1 second
    replace all "\w+" regex with "-" in lines 100K.txt: < 1 second

HippoEdit 1.60.18 x64:
    replace all "a+" regex with "-" in lines 100K.txt: 7 seconds
    replace all "\w+" regex with "-" in lines 100K.txt: test aborted after 3 minutes without result

SynWrite 6.18.2135:
    replace all "a+" regex with "-" in lines 100K.txt: 13 seconds
    replace all "\w+" regex with "-" in lines 100K.txt: test aborted after 3 minutes without result

ATSynEdit Finder Demo:
    replace all "a+" regex with "-" in lines 100K.txt: 38 seconds
    replace all "\w+" regex with "-" in lines 100K.txt: test aborted after 3 minutes without result

So I would say there is room for improvement :-) espcially in comparison with EditPad Pro and EmEditor.

**Comment by Alexey-T** [comment]
You're right- tks

**Comment by Alexey-T** [comment]
Moved to new msg
