### ISSUE TITLE
Problem with find backward

### ISSUE THREAD

**Issue by Andreas123456** [Alexey-T/ATSynEdit#87]
In the test text, place the caret at line 17, column 8 (i.e. behind the end of the line). Then search for "ddd" with the options "backward" and "from caret" activated. ==> The sting "ddd" will be found at column line 11, column 175. That's fine.

Now place the caret at line 18, column 8 (i.e. behind the end of the line). Then search for "ddd" with the options "backward" and "from caret" activated. ==> The sting "ddd" will be found at column line 20, column 3. That's not okay.

**Comment by Alexey-T** [comment]
Thank. Will search for bug
