### ISSUE TITLE
Problems with "confirm relace"

### ISSUE THREAD

**Issue by Andreas123456** [Alexey-T/ATSynEdit#90]
1. "yes" and "no" should not close the dialog window.

2. "Yes to All" does not replace all occurrences.

**Comment by Alexey-T** [comment]
Dlg is modal so cannot stAY open- i need close it
Sure yestoall not works? I tested again and regex "w+" replaced to "-" with yestoall in all file

**Comment by Andreas123456** [comment]
A solution is necessary where the dialog remains open after "yes" or "no". Otherwise the usability would be bad.

Yes, I'm sure that "Yes to All" does not work. Steps to reproduce:

1. Ctrl+F.
Find what: d
[x] Replace with: q
[ ] Regex
[ ] Case sensitive
[ ] Whole words only
[ ] Backward
[ ] From caret
[x] Confirm Replace

2. Press "Replace"

3. Press "Yes to All"

==> Only the first occurrence will be replaced, but it should replace all occurrences.

**Comment by Alexey-T** [comment]
hehe- "replace" is One replace. mass replace is "replaca all'

**Comment by Andreas123456** [comment]
Then what is the purpose of "Yes to All"?

**Comment by Alexey-T** [comment]
it's mistake to show it. it' s demo only

**Comment by Andreas123456** [comment]
Okay.

**Comment by Alexey-T** [comment]
Real app ll show ok Confirm dlg- like ST3 with dlg at bottom and not jumps on view
