### ISSUE TITLE
Speed of finder

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATSynEdit#93]
@Andreas123456 wrote:
Okay, here are some benchmark figures:

EditPad Pro 7.8.3 x64:
    replace all "a+" regex with "-" in lines 100K.txt: < 1 second
    replace all "\w+" regex with "-" in lines 100K.txt: < 1 second

EmEditor v15.2.0 beta 2 x64:
    replace all "a+" regex with "-" in lines 100K.txt: < 1 second
    replace all "\w+" regex with "-" in lines 100K.txt: < 1 second

HippoEdit 1.60.18 x64:
    replace all "a+" regex with "-" in lines 100K.txt: 7 seconds
    replace all "\w+" regex with "-" in lines 100K.txt: test aborted after 3 minutes without result

SynWrite 6.18.2135:
    replace all "a+" regex with "-" in lines 100K.txt: 13 seconds
    replace all "\w+" regex with "-" in lines 100K.txt: test aborted after 3 minutes without result

ATSynEdit Finder Demo:
    replace all "a+" regex with "-" in lines 100K.txt: 38 seconds
    replace all "\w+" regex with "-" in lines 100K.txt: test aborted after 3 minutes without result

So I would say there is room for improvement :-) espcially in comparison with EditPad Pro and EmEditor.

**Comment by Alexey-T** [comment]
maybe economied 1-2 sec. No speed can be better coz of algoritm. New algowith of find-replace needed(not now...) (i have idea. not now)

**Comment by Alexey-T** [comment]
@User4martin Can u please give advice? I see Lazarus ide is fast here. file "lines 100K.txt" replace '\w+' to - is 5-7 seconds. What i do is make string from TATStrings and do replace in it (after each replace i do string again)

**Comment by Alexey-T** [comment]
@Andreas123456 Cudatext Beta 1.9.1, MUCH faster. Pls test speed
http://uvviewsoft.com/bb/

**Comment by Andreas123456** [comment]
Okay, here are some new benchmark figures:

EditPad Pro 7.6.0 x64:
replace all "a+" regex with "-" in lines 100K.txt: < 1 second
replace all "\w+" regex with "-" in lines 100K.txt: < 1 second

CudaText 1.9.1.0 x64:
replace all "a+" regex with "-" in lines 100K.txt: 3 seconds
replace all "\w+" regex with "-" in lines 100K.txt: 71 seconds

So CudaText is still not as fast as EditPad Pro, but I would say it's fast enough. In my opinion, this issue can be regarded as fixed.

PS: The version number of EditPad Pro stated in the first posting of this thread is wrong. As of today, EditPad Pro 7.6.0 is the latest available version.

**Comment by Alexey-T** [comment]
70 sec  is long. Pls, share this file?

**Comment by Alexey-T** [comment]
I found 100K file here.
